table_4_2_10_0  = {
'0':['Wave Spectra (1)','-','WVSP1'],
'1':['Wave Spectra (2)','-','WVSP2'],
'2':['Wave Spectra (3)','-','WVSP3'],
'3':['Significant Height of Combined Wind Waves and Swell','m','HTSGW'],
'4':['Direction of Wind Waves','degree true','WVDIR'],
'5':['Significant Height of Wind Waves','m','WVHGT'],
'6':['Mean Period of Wind Waves','s','WVPER'],
'7':['Direction of Swell Waves','degree true','SWDIR'],
'8':['Significant Height of Swell Waves','m','SWELL'],
'9':['Mean Period of Swell Waves','s','SWPER'],
'10':['Primary Wave Direction','degree true','DIRPW'],
'11':['Primary Wave Mean Period','s','PERPW'],
'12':['Secondary Wave Direction','degree true','DIRSW'],
'13':['Secondary Wave Mean Period','s','PERSW'],
'14':['Direction of Combined Wind Waves and Swell','degree true','WWSDIR'],
'15':['Mean Period of Combined Wind Waves and Swell','s','MWSPER'],
'16':['Coefficient of Drag With Waves','-','CDWW'],
'17':['Friction Velocity','m s-1','FRICVW'],
'18':['Wave Stress','N m-2','WSTR'],
'19':['Normalised Waves Stress','-','NWSTR'],
'20':['Mean Square Slope of Waves','-','MSSW'],
'21':['U-component Surface Stokes Drift','m s-1','USSD'],
'22':['V-component Surface Stokes Drift','m s-1','VSSD'],
'23':['Period of Maximum Individual Wave Height','s','PMAXWH'],
'24':['Maximum Individual Wave Height','m','MAXWH'],
'25':['Inverse Mean Wave Frequency','s','IMWF'],
'26':['Inverse Mean Frequency of The Wind Waves','s','IMFWW'],
'27':['Inverse Mean Frequency of The Total Swell','s','IMFTSW'],
'28':['Mean Zero-Crossing Wave Period','s','MZWPER'],
'29':['Mean Zero-Crossing Period of The Wind Waves','s','MZPWW'],
'30':['Mean Zero-Crossing Period of The Total Swell','s','MZPTSW'],
'31':['Wave Directional Width','-','WDIRW'],
'32':['Directional Width of The Wind Waves','-','DIRWWW'],
'33':['Directional Width of The Total Swell','-','DIRWTS'],
'34':['Peak Wave Period','s','PWPER'],
'35':['Peak Period of The Wind Waves','s','PPERWW'],
'36':['Peak Period of The Total Swell','s','PPERTS'],
'37':['Altimeter Wave Height','m','ALTWH'],
'38':['Altimeter Corrected Wave Height','m','ALCWH'],
'39':['Altimeter Range Relative Correction','-','ALRRC'],
'40':['10 Metre Neutral Wind Speed Over Waves','m s-1','MNWSOW'],
'41':['10 Metre Wind Direction Over Waves','degree true','MWDIRW'],
'42':['Wave Engery Spectrum','m-2 s rad-1','WESP'],
'43':['Kurtosis of The Sea Surface Elevation Due to Waves','-','KSSEW'],
'44':['Benjamin-Feir Index','-','BENINX'],
'45':['Spectral Peakedness Factor','s-1','SPFTR'],
'46':['Peak wave direction','°','PWAVEDIR'],
'47':['Significant wave height of first swell partition','m','SWHFSWEL'],
'48':['Significant wave height of second swell partition','m','SWHSSWEL'],
'49':['Significant wave height of third swell partition','m','SWHTSWEL'],
'50':['Mean wave period of first swell partition','s','MWPFSWEL'],
'51':['Mean wave period of second swell partition','s','MWPSSWEL'],
'52':['Mean wave period of third swell partition','s','MWPTSWEL'],
'53':['Mean wave direction of first swell partition','°','MWDFSWEL'],
'54':['Mean wave direction of second swell partition','°','MWDSSWEL'],
'55':['Mean wave direction of third swell partition','°','MWDTSWEL'],
'56':['Wave directional width of first swell partition','-','WDWFSWEL'],
'57':['Wave directional width of second swell partition','-','WDWSSWEL'],
'58':['Wave directional width of third swell partition','-','WDWTSWEL'],
'59':['Wave frequency width of first swell partition','-','WFWFSWEL'],
'60':['Wave frequency width of second swell partition','-','WFWSSWEL'],
'61':['Wave frequency width of third swell partition','-','WFWTSWEL'],
'62':['Wave frequency width','-','WAVEFREW'],
'63':['Frequency width of wind waves','-','FREWWW'],
'64':['Frequency width of total swell','-','FREWTSW'],
'65':['Peak Wave Period of First Swell Partition','s','PWPFSPAR'],
'66':['Peak Wave Period of Second Swell Partition','s','PWPSSPAR'],
'67':['Peak Wave Period of Third Swell Partition','s','PWPTSPAR'],
'68':['Peak Wave Direction of First Swell Partition','degree true','PWDFSPAR'],
'69':['Peak Wave Direction of Second Swell Partition','degree true','PWDSSPAR'],
'70':['Peak Wave Direction of Third Swell Partition','degree true','PWDTSPAR'],
'71':['Peak Direction of Wind Waves','degree true','PDWWAVE'],
'72':['Peak Direction of Total Swell','degree true','PDTSWELL'],
'73':['Whitecap Fraction','fraction','WCAPFRAC'],
'74':['Mean Direction of Total Swell','degree','MDTSWEL'],
'75':['Mean Direction of Wind Waves','degree','MDWWAVE'],
'76':['Charnock','Numeric','CHNCK'],
'77':['Wave Spectral Skewness','Numeric','WAVESPSK'],
'78':['Wave Energy Flux Magnitude','W m-1','WAVEFMAG'],
'79':['Wave Energy Flux Mean Direction','degree true','WAVEFDIR'],
'80':['Ratio of Wave Angular and Frequency Width','Numeric','RWAVEAFW'],
'81':['Free Convective Velocity over the Oceans','m s-1','FCVOCEAN'],
'82':['Air Density over the Oceans','kg m-3','AIRDENOC'],
'83':['Normalized Energy Flux into Waves','Numeric','NEFW'],
'84':['Normalized Stress into Ocean','Numeric','NSOCEAN'],
'85':['Normalized Energy Flux into Ocean','Numeric','NEFOCEAN'],
'86':['Surface Elevation Variance due to Waves (over all frequencies and directions)','m2 s rad-1','SEVWAVE'],
'87':['Wave Induced Mean Sea Level Correction','m','WAVEMSLC'],
'88':['Spectral Width Index','Numeric','SPECWI'],
'89':['Number of Events in Freak Wave Statistics','Numeric','EFWS'],
'90':['U-Component of Surface Momentum Flux into Ocean','N m-2','USMFO'],
'91':['U-Component of Surface Momentum Flux into Ocean','N m-2','VSMFO'],
'92':['Wave Turbulent Energy Flux into Ocean','W m-2','WAVETEFO'],
'93':['Envelop maximum individual wave height','m','EMIWAVE'],
'94':['Time domain maximum individual crest height','m','TDMCREST'],
'95':['Time domain maximum individual wave height','m','TDMWAVE'],
'96':['Space time maximum individual crest height','m','STMCREST'],
'97':['Space time maximum individual wave height','m','STMWAVE'],
'98':['Goda peakedness factor','Numeric','GODAPEAK'],
'99':['Benjamin-Feir Index 2D (BFI2D)','Numeric','BFI2D'],
'100':['Crest-Trough Correlation','Numeric','CTCORR'],
'101':['X-Component of the Wave Radiative Stress to Sea Ice','N m-2','WSTRICEX'],
'102':['Y-Component of the Wave Radiative Stress to Sea Ice','N m-2','WSTRICEY'],
table_4_2_10_1  = {
'0':['Current Direction','degree True','DIRC'],
'1':['Current Speed','m s-1','SPC'],
'2':['U-Component of Current','m s-1','UOGRD'],
'3':['V-Component of Current','m s-1','VOGRD'],
'4':['Rip Current Occurrence Probability','%','RIPCOP'],
'5':['Eastward Current','m s-1','EASTCUR'],
'6':['Northward Current','m s-1','NRTHCUR'],
table_4_2_10_2  = {
'0':['Ice Cover','Proportion','ICEC'],
'1':['Ice Thickness','m','ICETK'],
'2':['Direction of Ice Drift','degree True','DICED'],
'3':['Speed of Ice Drift','m s-1','SICED'],
'4':['U-Component of Ice Drift','m s-1','UICE'],
'5':['V-Component of Ice Drift','m s-1','VICE'],
'6':['Ice Growth Rate','m s-1','ICEG'],
'7':['Ice Divergence','s-1','ICED'],
'8':['Ice Temperature','K','ICETMP'],
'9':['Module of Ice Internal Pressure','Pa m','ICEPRS'],
'10':['Zonal Vector Component of Vertically Integrated Ice Internal Pressure','Pa m','ZVCICEP'],
'11':['Meridional Vector Component of Vertically Integrated Ice Internal Pressure','Pa m','MVCICEP'],
'12':['Compressive Ice Strength','N m-1','CICES'],
'13':['Snow Temperature (over sea ice)','K','SNOWTSI'],
'14':['Albedo','Numeric','ALBDOICE'],
'15':['Sea Ice Volume per Unit Area','m3m-2','SICEVOL'],
'16':['Snow Volume Over Sea Ice per Unit Area','m3m-2','SNVOLSI'],
'17':['Sea Ice Heat Content','J m-2','SICEHC'],
'18':['Snow over Sea Ice Heat Content','J m-2','SNCEHC'],
'19':['Ice Freeboard Thickness','m','ICEFTHCK'],
'20':['Ice Melt Pond Fraction','fraction','ICEMPF'],
'21':['Ice Melt Pond Depth','m','ICEMPD'],
'22':['Ice Melt Pond Volume per Unit Area','m3m-2','ICEMPV'],
'23':['Sea Ice Fraction Tendency due to Parameterization','s-1','SIFTP'],
'24':['X-Component of Ice Drift','m s-1','XICE'],
'25':['Y-Component of Ice Drift','m s-1','YICE'],
'26':['Sea Ice Salinity','g kg-1','SICESAL'],
'27':['Freezing/Melting Potential','W m-2','FRZMLTPOT'],
'28':['Melt Onset Date','Numeric','MLTDATE'],
'29':['Freeze Onset Date','Numeric','FRZDATE'],
'30':['Sea Ice Breakup Memory','Numeric','SICEBM'],
'31':['Downward Shortwave Radiation Flux','W m-2','DSWRFICE'],
table_4_2_10_3  = {
'0':['Water Temperature','K','WTMP'],
'1':['Deviation of Sea Level from Mean','m','DSLM'],
table_4_2_10_4  = {
'0':['Main Thermocline Depth','m','MTHD'],
'1':['Main Thermocline Anomaly','m','MTHA'],
'2':['Transient Thermocline Depth','m','TTHDP'],
'3':['Salinity','kg kg-1','SALTY'],
'4':['Ocean Vertical Heat Diffusivity','m2 s-1','OVHD'],
'5':['Ocean Vertical Salt Diffusivity','m2 s-1','OVSD'],
'6':['Ocean Vertical Momentum Diffusivity','m2 s-1','OVMD'],
'7':['Bathymetry','m','BATHY'],
table_4_2_10_191  = {
'0':['Seconds Prior To Initial Reference Time (Defined In Section 1)','s','IRTSEC'],
'1':['Meridional Overturning Stream Function','m3 s-1','MOSF'],
