table_4_2_20_0  = {
'0':['Universal Thermal Climate Index','K','UTHCIDX'],
'1':['Mean Radiant Temperature','K','MEANRTMP'],
'2':['Wet-Bulb Globe Temperature','K','WETBGTMP'],
'3':['Globe Temperature','K','GLOBETMP'],
'4':['Humidex','K','HUMIDX'],
'5':['Effective Temperature','K','EFFTEMP'],
'6':['Normal Effective Temperature','K','NOREFTMP'],
'7':['Standard Effective Temperature','K','STDEFTMP'],
'8':['Physiological Equivalent Temperature','K','PEQUTMP'],
'9':['UV Biologically Effective Dose','W m-2','UVBED'],
'10':['UV Biologically Effective Dose, Clear-Sky','W m-2','UVBEDCS'],
'11':['Excess Heat Factor','K2','EHF'],
'12':['Excess Cold Factor','K2','ECF'],
table_4_2_20_1  = {
'0':['Malaria Cases','Fraction','MALACASE'],
'1':['Malaria Circumsporozoite Protein Rate','Fraction','MACPRATE'],
'2':['Plasmodium Falciparum Entomological Inoculation Rate','Bites per day per person','PFEIRATE'],
'3':['Human Bite Rate by Anopheles Vectors','Bites per day per person','HBRATEAV'],
'4':['Malaria Immunity','Fraction','MALAIMM'],
'5':['Falciparum Parasite Rates','Fraction','FALPRATE'],
'6':['Detectable Falciparum Parasite Ratio (after day 10)','Fraction','DFPRATIO'],
'7':['Anopheles Vector to Host Ratio','Fraction','AVHRATIO'],
'8':['Anopheles Vector Number','Number m-2','AVECTNUM'],
'9':['Fraction of Malarial Vector Reproductive Habitat','Fraction','FMALVRH'],
table_4_2_20_2  = {
'0':['Population Density','Person m-2','POPDEN'],
