table_4_2_0_0  = {
'0':['Temperature','K','TMP'],
'1':['Virtual Temperature','K','VTMP'],
'2':['Potential Temperature','K','POT'],
'3':['Pseudo-Adiabatic Potential Temperature (or Equivalent Potential Temperature)','K','EPOT'],
'4':['Maximum Temperature','K','TMAX'],
'5':['Minimum Temperature','K','TMIN'],
'6':['Dew Point Temperature','K','DPT'],
'7':['Dew Point Depression (or Deficit)','K','DEPR'],
'8':['Lapse Rate','K m-1','LAPR'],
'9':['Temperature Anomaly','K','TMPA'],
'10':['Latent Heat Net Flux','W m-2','LHTFL'],
'11':['Sensible Heat Net Flux','W m-2','SHTFL'],
'12':['Heat Index','K','HEATX'],
'13':['Wind Chill Factor','K','WCF'],
'14':['Minimum Dew Point Depression','K','MINDPD'],
'15':['Virtual Potential Temperature','K','VPTMP'],
'16':['Snow Phase Change Heat Flux','W m-2','SNOHF'],
'17':['Skin Temperature','K','SKINT'],
'18':['Snow Temperature (top of snow)','K','SNOT'],
'19':['Turbulent Transfer Coefficient for Heat','Numeric','TTCHT'],
'20':['Turbulent Diffusion Coefficient for Heat','m2s-1','TDCHT'],
'21':['Apparent Temperature','K','APTMP'],
'22':['Temperature Tendency due to Short-Wave Radiation','K s-1','TTSWR'],
'23':['Temperature Tendency due to Long-Wave Radiation','K s-1','TTLWR'],
'24':['Temperature Tendency due to Short-Wave Radiation, Clear Sky','K s-1','TTSWRCS'],
'25':['Temperature Tendency due to Long-Wave Radiation, Clear Sky','K s-1','TTLWRCS'],
'26':['Temperature Tendency due to parameterizations','K s-1','TTPARM'],
'27':['Wet Bulb Temperature','K','WETBT'],
'28':['Unbalanced Component of Temperature','K','UCTMP'],
'29':['Temperature Advection','K s-1','TMPADV'],
'30':['Latent Heat Net Flux Due to Evaporation','W m-2','LHFLXE'],
'31':['Latent Heat Net Flux Due to Sublimation','W m-2','LHFLXS'],
'32':['Wet-Bulb Potential Temperature','K','WETBPT'],
table_4_2_0_1  = {
'0':['Specific Humidity','kg kg-1','SPFH'],
'1':['Relative Humidity','%','RH'],
'2':['Humidity Mixing Ratio','kg kg-1','MIXR'],
'3':['Precipitable Water','kg m-2','PWAT'],
'4':['Vapour Pressure','Pa','VAPP'],
'5':['Saturation Deficit','Pa','SATD'],
'6':['Evaporation','kg m-2','EVP'],
'7':['Precipitation Rate','kg m-2 s-1','PRATE'],
'8':['Total Precipitation','kg m-2','APCP'],
'9':['Large-Scale Precipitation (non-convective)','kg m-2','NCPCP'],
'10':['Convective Precipitation','kg m-2','ACPCP'],
'11':['Snow Depth','m','SNOD'],
'12':['Snowfall Rate Water Equivalent','kg m-2 s-1','SRWEQ'],
'13':['Water Equivalent of Accumulated Snow Depth','kg m-2','WEASD'],
'14':['Convective Snow','kg m-2','SNOC'],
'15':['Large-Scale Snow','kg m-2','SNOL'],
'16':['Snow Melt','kg m-2','SNOM'],
'17':['Snow Age','day','SNOAG'],
'18':['Absolute Humidity','kg m-3','ABSH'],
'19':['Precipitation Type','See Table 4.201','PTYPE'],
'20':['Integrated Liquid Water','kg m-2','ILIQW'],
'21':['Condensate','kg kg-1','TCOND'],
'22':['Cloud Mixing Ratio','kg kg-1','CLMR'],
'23':['Ice Water Mixing Ratio','kg kg-1','ICMR'],
'24':['Rain Mixing Ratio','kg kg-1','RWMR'],
'25':['Snow Mixing Ratio','kg kg-1','SNMR'],
'26':['Horizontal Moisture Convergence','kg kg-1 s-1','MCONV'],
'27':['Maximum Relative Humidity','%','MAXRH'],
'28':['Maximum Absolute Humidity','kg m-3','MAXAH'],
'29':['Total Snowfall','m','ASNOW'],
'30':['Precipitable Water Category','See Table 4.202','PWCAT'],
'31':['Hail','m','HAIL'],
'32':['Graupel','kg kg-1','GRLE'],
'33':['Categorical Rain','Code table 4.222','CRAIN'],
'34':['Categorical Freezing Rain','Code table 4.222','CFRZR'],
'35':['Categorical Ice Pellets','Code table 4.222','CICEP'],
'36':['Categorical Snow','Code table 4.222','CSNOW'],
'37':['Convective Precipitation Rate','kg m-2 s-1','CPRAT'],
'38':['Horizontal Moisture Divergence','kg kg-1 s-1','MDIVER'],
'39':['Percent frozen precipitation','%','CPOFP'],
'40':['Potential Evaporation','kg m-2','PEVAP'],
'41':['Potential Evaporation Rate','W m-2','PEVPR'],
'42':['Snow Cover','%','SNOWC'],
'43':['Rain Fraction of Total Cloud Water','Proportion','FRAIN'],
'44':['Rime Factor','Numeric','RIME'],
'45':['Total Column Integrated Rain','kg m-2','TCOLR'],
'46':['Total Column Integrated Snow','kg m-2','TCOLS'],
'47':['Large Scale Water Precipitation (Non-Convective)','kg m-2','LSWP'],
'48':['Convective Water Precipitation','kg m-2','CWP'],
'49':['Total Water Precipitation','kg m-2','TWATP'],
'50':['Total Snow Precipitation','kg m-2','TSNOWP'],
'51':['Total Column Water (Vertically integrated total water (vapour+cloud water/ice)','kg m-2','TCWAT'],
'52':['Total Precipitation Rate','kg m-2 s-1','TPRATE'],
'53':['Total Snowfall Rate Water Equivalent','kg m-2 s-1','TSRWE'],
'54':['Large Scale Precipitation Rate','kg m-2 s-1','LSPRATE'],
'55':['Convective Snowfall Rate Water Equivalent','kg m-2 s-1','CSRWE'],
'56':['Large Scale Snowfall Rate Water Equivalent','kg m-2 s-1','LSSRWE'],
'57':['Total Snowfall Rate','m s-1','TSRATE'],
'58':['Convective Snowfall Rate','m s-1','CSRATE'],
'59':['Large Scale Snowfall Rate','m s-1','LSSRATE'],
'60':['Snow Depth Water Equivalent','kg m-2','SDWE'],
'61':['Snow Density','kg m-3','SDEN'],
'62':['Snow Evaporation','kg m-2','SEVAP'],
table_4_2_0_2  = {
'0':['Wind Direction (from which blowing)','°','WDIR'],
'1':['Wind Speed','m s-1','WIND'],
'2':['U-Component of Wind','m s-1','UGRD'],
'3':['V-Component of Wind','m s-1','VGRD'],
'4':['Stream Function','m2 s-1','STRM'],
'5':['Velocity Potential','m2 s-1','VPOT'],
'6':['Montgomery Stream Function','m2 s-2','MNTSF'],
'7':['Sigma Coordinate Vertical Velocity','s-1','SGCVV'],
'8':['Vertical Velocity (Pressure)','Pa s-1','VVEL'],
'9':['Vertical Velocity (Geometric)','m s-1','DZDT'],
'10':['Absolute Vorticity','s-1','ABSV'],
'11':['Absolute Divergence','s-1','ABSD'],
'12':['Relative Vorticity','s-1','RELV'],
'13':['Relative Divergence','s-1','RELD'],
'14':['Potential Vorticity','K m2 kg-1 s-1','PVORT'],
'15':['Vertical U-Component Shear','s-1','VUCSH'],
'16':['Vertical V-Component Shear','s-1','VVCSH'],
'17':['Momentum Flux, U-Component','N m-2','UFLX'],
'18':['Momentum Flux, V-Component','N m-2','VFLX'],
'19':['Wind Mixing Energy','J','WMIXE'],
'20':['Boundary Layer Dissipation','W m-2','BLYDP'],
'21':['Maximum Wind Speed','m s-1','MAXGUST'],
'22':['Wind Speed (Gust)','m s-1','GUST'],
'23':['U-Component of Wind (Gust)','m s-1','UGUST'],
'24':['V-Component of Wind (Gust)','m s-1','VGUST'],
'25':['Vertical Speed Shear','s-1','VWSH'],
'26':['Horizontal Momentum Flux','N m-2','MFLX'],
'27':['U-Component Storm Motion','m s-1','USTM'],
'28':['V-Component Storm Motion','m s-1','VSTM'],
'29':['Drag Coefficient','Numeric','CD'],
'30':['Frictional Velocity','m s-1','FRICV'],
'31':['Turbulent Diffusion Coefficient for Momentum','m2 s-1','TDCMOM'],
'32':['Eta Coordinate Vertical Velocity','s-1','ETACVV'],
'33':['Wind Fetch','m','WINDF'],
'34':['Normal Wind Component','m s-1','NWIND'],
'35':['Tangential Wind Component','m s-1','TWIND'],
'36':['Amplitude Function for Rossby Wave Envelope for Meridional Wind','m s-1','AFRWE'],
'37':['Northward Turbulent Surface Stress (see Notes 4 and 7)','N m-2 s','NTSS'],
'38':['Eastward Turbulent Surface Stress (see Notes 4 and 7)','N m-2 s','ETSS'],
'39':['Eastward Wind Tendency Due to Parameterizations','m s-2','EWTPARM'],
'40':['Northward Wind Tendency Due to Parameterizations','m s-2','NWTPARM'],
'41':['U-Component of Geostrophic Wind','m s-1','UGWIND'],
'42':['V-Component of Geostrophic Wind','m s-1','VGWIND'],
'43':['Geostrophic Wind Direction','°','GEOWD'],
'44':['Geostrophic Wind Speed','m s-1','GEOWS'],
'45':['Unbalanced Component of Divergence','s-1','UNDIV'],
'46':['Vorticity Advection','s-2','VORTADV'],
'47':['Surface roughness for heat,(see Note 5)','m','SFRHEAT'],
'48':['Surface roughness for moisture,(see Note 6)','m','SFRMOIST'],
'49':['Wind stress','N m-2','WINDSTR'],
'50':['Eastward wind stress','N m-2','EWINDSTR'],
'51':['Northward wind stress','N m-2','NWINDSTR'],
'52':['u-component of wind stress','N m-2','UWINDSTR'],
'53':['v-component of wind stress','N m-2','VWINDSTR'],
'54':['Natural logarithm of surface roughness length for heat','m','NLSRLH'],
'55':['Natural logarithm of surface roughness length for moisture','m','NLSRLM'],
'56':['u-component of neutral wind','m s-1','UNWIND'],
'57':['v-component of neutral wind','m s-1','VNWIND'],
'58':['Magnitude of turbulent surface stress','N m-2','TSFCSTR'],
'59':['Vertical divergence','s-1','VDIV'],
'60':['Drag thermal coefficient','Numeric','DTC'],
'61':['Drag evaporation coefficient','Numeric','DEC'],
'62':['Eastward turbulent surface stress','N m-2','EASTTSS'],
'63':['Northward turbulent surface stress','N m-2','NRTHTSS'],
'64':['Eastward turbulent surface stress due to orographic form drag','N m-2','EASTTSSOD'],
'65':['Northward turbulent surface stress due to orographic form drag','N m-2','NRTHTSSOD'],
'66':['Eastward turbulent surface stress due to surface roughness','N m-2','EASTTSSSR'],
'67':['Northward turbulent surface stress due to surface roughness','N m-2','NRTHTSSSR'],
'68':['Convective Gust','m s-1','CNVGUST'],
'69':['Turbulent Gust','m s-1','TURBGUST'],
table_4_2_0_3  = {
'0':['Pressure','Pa','PRES'],
'1':['Pressure Reduced to MSL','Pa','PRMSL'],
'2':['Pressure Tendency','Pa s-1','PTEND'],
'3':['ICAO Standard Atmosphere Reference Height','m','ICAHT'],
'4':['Geopotential','m2 s-2','GP'],
'5':['Geopotential Height','gpm','HGT'],
'6':['Geometric Height','m','DIST'],
'7':['Standard Deviation of Height','m','HSTDV'],
'8':['Pressure Anomaly','Pa','PRESA'],
'9':['Geopotential Height Anomaly','gpm','GPA'],
'10':['Density','kg m-3','DEN'],
'11':['Altimeter Setting','Pa','ALTS'],
'12':['Thickness','m','THICK'],
'13':['Pressure Altitude','m','PRESALT'],
'14':['Density Altitude','m','DENALT'],
'15':['5-Wave Geopotential Height','gpm','5WAVH'],
'16':['Zonal Flux of Gravity Wave Stress','N m-2','U-GWD'],
'17':['Meridional Flux of Gravity Wave Stress','N m-2','V-GWD'],
'18':['Planetary Boundary Layer Height','m','HPBL'],
'19':['5-Wave Geopotential Height Anomaly','gpm','5WAVA'],
'20':['Standard Deviation of Sub-Grid Scale Orography','m','SDSGSO'],
'21':['Angle of Sub-Grid Scale Orography','rad','AOSGSO'],
'22':['Slope of Sub-Grid Scale Orography','Numeric','SSGSO'],
'23':['Gravity Wave Dissipation','W m-2','GWD'],
'24':['Anisotropy of Sub-Grid Scale Orography','Numeric','ASGSO'],
'25':['Natural Logarithm of Pressure in Pa','Numeric','NLPRES'],
'26':['Exner Pressure','Numeric','EXPRES'],
'27':['Updraught Mass Flux','kg m-2 s-1','UMFLX'],
'28':['Downdraught Mass Flux','kg m-2 s-1','DMFLX'],
'29':['Updraught Detrainment Rate','kg m-3 s-1','UDRATE'],
'30':['Downdraught Detrainment Rate','kg m-3 s-1','DDRATE'],
'31':['Unbalanced Component of Logarithm of Surface Pressure','-','UCLSPRS'],
'32':['Saturation water vapour pressure','Pa','SWATERVP'],
'33':['Geometric altitude above mean sea level','m','GAMSL'],
'34':['Geometric height above ground level','m','GHAGRD'],
'35':['Column integrated divergence of total mass flux','kg m-2 s-1','CDTMF'],
'36':['Column integrated eastward total mass flux','kg m-2 s-1','CETMF'],
'37':['Column integrated northward total mass flux','kg m-2 s-1','CNTMF'],
'38':['Standard deviation of filteblack subgrid orography','m','SDFSO'],
'39':['Column integrated mass of atmosphere','kg m-2 s-1','CMATMOS'],
'40':['Column integrated eastward geopotential flux','W m-1','CEGFLUX'],
'41':['Column integrated northward geopotential flux','W m-1','CNGFLUX'],
'42':['Column integrated divergence of water geopotential flux','W m-2','CDWGFLUX'],
'43':['Column integrated divergence of geopotential flux','W m-2','CDGFLUX'],
'44':['Height of zero-degree wet-bulb temperature','m','HWBT'],
'45':['Height of one-degree wet-bulb temperature','m','WOBT'],
'46':['Pressure departure from hydrostatic state','Pa','PRESDHS'],
table_4_2_0_4  = {
'0':['Net Shortwave Radiation Flux (Surface)','W m-2','NSWRS'],
'1':['Net Shortwave Radiation Flux (Top of Atmosphere)','W m-2','NSWRT'],
'2':['Shortwave Radiation Flux','W m-2','SWAVR'],
'3':['Global Radiation Flux','W m-2','GRAD'],
'4':['Brightness Temperature','K','BRTMP'],
'5':['Radiance (with respect to wave number)','W m-1 sr-1','LWRAD'],
'6':['Radiance (with respect to wavelength)','W m-3 sr-1','SWRAD'],
'7':['Downward Shortwave Radiation Flux','W m-2','DSWRF'],
'8':['Upward Shortwave Radiation Flux','W m-2','USWRF'],
'9':['Net Shortwave Radiation Flux','W m-2','NSWRF'],
'10':['Photosynthetically Active Radiation','W m-2','PHOTAR'],
'11':['Net Shortwave Radiation Flux, Clear Sky','W m-2','NSWRFCS'],
'12':['Downward UV Radiation','W m-2','DWUVR'],
'13':['Direct Shortwave Radiation Flux','W m-2','DSWRFLX'],
'14':['Diffuse Shortwave Radiation Flux','W m-2','DIFSWRF'],
'15':['Upward UV radiation emitted/reflected from the Earths surface','W m-2','UVVEARTH'],
table_4_2_0_5  = {
'0':['Net Longwave Radiation Flux (Surface)','W m-2','NLWRS'],
'1':['Net Longwave Radiation Flux (Top of Atmosphere)','W m-2','NLWRT'],
'2':['Longwave Radiation Flux','W m-2','LWAVR'],
'3':['Downward Longwave Radiation Flux','W m-2','DLWRF'],
'4':['Upward Longwave Radiation Flux','W m-2','ULWRF'],
'5':['Net Longwave Radiation Flux','W m-2','NLWRF'],
'6':['Net Longwave Radiation Flux, Clear Sky','W m-2','NLWRCS'],
'7':['Brightness Temperature','K','BRTEMP'],
'8':['Downward Longwave Radiation Flux, Clear Sky','W m-2','DLWRFCS'],
'9':['Near IR albedo for diffuse radiation','%','NIRALBDIF'],
'10':['Near IR albedo for direct radiation','%','NIRALBDIR'],
'11':['Near IR albedo for direct radiation, geometric component','%','NIRALBDIRG'],
'12':['Near IR albedo for direct radiation, isotropic component','%','NIRALBDIRI'],
'13':['Near IR albedo for direct radiation, volumetric component','%','NIRALBDIRV'],
table_4_2_0_6  = {
'0':['Cloud Ice','kg m-2','CICE'],
'1':['Total Cloud Cover','%','TCDC'],
'2':['Convective Cloud Cover','%','CDCON'],
'3':['Low Cloud Cover','%','LCDC'],
'4':['Medium Cloud Cover','%','MCDC'],
'5':['High Cloud Cover','%','HCDC'],
'6':['Cloud Water','kg m-2','CWAT'],
'7':['Cloud Amount','%','CDCA'],
'8':['Cloud Type','See Table 4.203','CDCT'],
'9':['Thunderstorm Maximum Tops','m','TMAXT'],
'10':['Thunderstorm Coverage','See Table 4.204','THUNC'],
'11':['Cloud Base','m','CDCB'],
'12':['Cloud Top','m','CDCTOP'],
'13':['Ceiling','m','CEIL'],
'14':['Non-Convective Cloud Cover','%','CDLYR'],
'15':['Cloud Work Function','J kg-1','CWORK'],
'16':['Convective Cloud Efficiency','Proportion','CUEFI'],
'17':['Total Condensate','kg kg-1','TCONDO'],
'18':['Total Column-Integrated Cloud Water','kg m-2','TCOLWO'],
'19':['Total Column-Integrated Cloud Ice','kg m-2','TCOLIO'],
'20':['Total Column-Integrated Condensate','kg m-2','TCOLC'],
'21':['Ice fraction of total condensate','Proportion','FICE'],
'22':['Cloud Cover','%','CDCC'],
'23':['Cloud Ice Mixing Ratio','kg kg-1','CDCIMR'],
'24':['Sunshine','Numeric','SUNS'],
'25':['Horizontal Extent of Cumulonimbus (CB)','%','CBHE'],
'26':['Height of Convective Cloud Base','m','HCONCB'],
'27':['Height of Convective Cloud Top','m','HCONCT'],
'28':['Number Concentration of Cloud Droplets','kg-1','NCONCD'],
'29':['Number Concentration of Cloud Ice','kg-1','NCCICE'],
'30':['Number Density of Cloud Droplets','m-3','NDENCD'],
'31':['Number Density of Cloud Ice','m-3','NDCICE'],
'32':['Fraction of Cloud Cover','Numeric','FRACCC'],
'33':['Sunshine Duration','s','SUNSD'],
'34':['Surface Long Wave Effective Total Cloudiness','Numeric','SLWTC'],
'35':['Surface Short Wave Effective Total Cloudiness','Numeric','SSWTC'],
'36':['Fraction of Stratiform Precipitation Cover','Proportion','FSTRPC'],
'37':['Fraction of Convective Precipitation Cover','Proportion','FCONPC'],
'38':['Mass Density of Cloud Droplets','kg m-3','MASSDCD'],
'39':['Mass Density of Cloud Ice','kg m-3','MASSDCI'],
'40':['Mass Density of Convective Cloud Water Droplets','kg m-3','MDCCWD'],
table_4_2_0_7  = {
'0':['Parcel Lifted Index (to 500 hPa)','K','PLI'],
'1':['Best Lifted Index (to 500 hPa)','K','BLI'],
'2':['K Index','K','KX'],
'3':['KO Index','K','KOX'],
'4':['Total Totals Index','K','TOTALX'],
'5':['Sweat Index','Numeric','SX'],
'6':['Convective Available Potential Energy','J kg-1','CAPE'],
'7':['Convective Inhibition','J kg-1','CIN'],
'8':['Storm Relative Helicity','m2 s-2','HLCY'],
'9':['Energy Helicity Index','Numeric','EHLX'],
'10':['Surface Lifted Index','K','LFTX'],
'11':['Best (4 layer) Lifted Index','K','4LFTX'],
'12':['Richardson Number','Numeric','RI'],
'13':['Showalter Index','K','SHWINX'],
table_4_2_0_13  = {
'0':['Aerosol Type','See Table 4.205','AEROT'],
table_4_2_0_14  = {
'0':['Total Ozone','DU','TOZNE'],
'1':['Ozone Mixing Ratio','kg kg-1','O3MR'],
'2':['Total Column Integrated Ozone','DU','TCIOZ'],
table_4_2_0_15  = {
'0':['Base Spectrum Width','m s-1','BSWID'],
'1':['Base Reflectivity','dB','BREF'],
'2':['Base Radial Velocity','m s-1','BRVEL'],
'3':['Vertically-Integrated Liquid Water','kg m-2','VIL'],
'4':['Layer Maximum Base Reflectivity','dB','LMAXBR'],
'5':['Precipitation','kg m-2','PREC'],
table_4_2_0_16  = {
'0':['Equivalent radar reflectivity factor for rain','m m6 m-3','REFZR'],
'1':['Equivalent radar reflectivity factor for snow','m m6 m-3','REFZI'],
'2':['Equivalent radar reflectivity factor for parameterized convection','m m6 m-3','REFZC'],
'3':['Echo Top','m','RETOP'],
'4':['Reflectivity','dB','REFD'],
'5':['Composite reflectivity','dB','REFC'],
'6':['Precipitation Rate','kg m-2s-1','PRATEFRAD'],
table_4_2_0_17  = {
'0':['Lightning Strike Density','m-2 s-1','LTNGSD'],
'1':['Lightning Potential Index (LPI)','J kg-1','LTPINX'],
'2':['Cloud-to-Ground Lightning Flash Density','km-2 day-1','CDGDLTFD'],
'3':['Cloud-to-Cloud Lightning Flash Density','km-2 day-1','CDCDLTFD'],
'4':['Total Lightning Flash Density','km-2 day-1','TLGTFD'],
'5':['Subgrid-scale Lightning Potential Index','J kg-1','SLNGPIDX'],
table_4_2_0_18  = {
'0':['Air Concentration of Caesium 137','Bq m-3','ACCES'],
'1':['Air Concentration of Iodine 131','Bq m-3','ACIOD'],
'2':['Air Concentration of Radioactive Pollutant','Bq m-3','ACRADP'],
'3':['Ground Deposition of Caesium 137','Bq m-2','GDCES'],
'4':['Ground Deposition of Iodine 131','Bq m-2','GDIOD'],
'5':['Ground Deposition of Radioactive Pollutant','Bq m-2','GDRADP'],
'6':['Time Integrated Air Concentration of Cesium Pollutant','Bq s m-3','TIACCP'],
'7':['Time Integrated Air Concentration of Iodine Pollutant','Bq s m-3','TIACIP'],
'8':['Time Integrated Air Concentration of Radioactive Pollutant','Bq s m-3','TIACRP'],
table_4_2_0_19  = {
'0':['Visibility','m','VIS'],
'1':['Albedo','%','ALBDO'],
'2':['Thunderstorm Probability','%','TSTM'],
'3':['Mixed Layer Depth','m','MIXHT'],
'4':['Volcanic Ash','See Table 4.206','VOLASH'],
'5':['Icing Top','m','ICIT'],
'6':['Icing Base','m','ICIB'],
'7':['Icing','See Table 4.207','ICI'],
'8':['Turbulence Top','m','TURBT'],
'9':['Turbulence Base','m','TURBB'],
'10':['Turbulence','See Table 4.208','TURB'],
'11':['Turbulent Kinetic Energy','J kg-1','TKE'],
'12':['Planetary Boundary Layer Regime','See Table 4.209','PBLREG'],
'13':['Contrail Intensity','See Table 4.210','CONTI'],
'14':['Contrail Engine Type','See Table 4.211','CONTET'],
'15':['Contrail Top','m','CONTT'],
'16':['Contrail Base','m','CONTB'],
'17':['Maximum Snow Albedo','%','MXSALB'],
'18':['Snow-Free Albedo','%','SNFALB'],
'19':['Snow Albedo','%','SALBD'],
'20':['Icing','%','ICIP'],
'21':['In-Cloud Turbulence','%','CTP'],
'22':['Clear Air Turbulence (CAT)','%','CAT'],
'23':['Supercooled Large Droplet Probability','%','SLDP'],
'24':['Convective Turbulent Kinetic Energy','J kg-1','CONTKE'],
'25':['Weather','See Table 4.225','WIWW'],
'26':['Convective Outlook','See Table 4.224','CONVO'],
'27':['Icing Scenario','See Table 4.227','ICESC'],
'28':['Mountain Wave Turbulence (Eddy Dissipation Rate)','m2/3 s-1','MWTURB'],
'29':['Clear Air Turbulence (CAT) (Eddy Dissipation Rate)','m2/3 s-1','CATEDR'],
'30':['Eddy Dissipation Parameter','m2/3 s-1','EDPARM'],
'31':['Maximum of Eddy Dissipation Parameter in Layer','m2/3 s-1','MXEDPRM'],
'32':['Highest Freezing Level','m','HIFREL'],
'33':['Visibility Through Liquid Fog','m','VISLFOG'],
'34':['Visibility Through Ice Fog','m','VISIFOG'],
'35':['Visibility Through Blowing Snow','m','VISBSN'],
'36':['Presence of Snow Squalls','See Table 4.222','PSNOWS'],
'37':['Icing Severity','See Table 4.228','ICESEV'],
'38':['Sky transparency index','See Table 4.214','SKYIDX'],
'39':['Seeing index','See Table 4.214','SEEINDEX'],
'40':['Snow level','m','SNOWLVL'],
'41':['Duct base height','m','DBHEIGHT'],
'42':['Trapping layer base height','m','TLBHEIGHT'],
'43':['Trapping layer top height','m','TLTHEIGHT'],
'44':['Mean vertical gradient of refractivity inside trapping layer','m-1','MEANVGRTL'],
'45':['Minimum vertical gradient of refractivity inside trapping layer','m-1','MINVGRTL'],
'46':['Net radiation flux','W m-2','NETRADFLUX'],
'47':['Global irradiance on tilted surfaces','W m-2','GLIRRTS'],
'48':['Top of persistent contrails','m','PCONTT'],
'49':['Base of persistent contrails','m','PCONTB'],
'50':['Convectively-induced turbulence (CIT) (eddy dissipation rate)','m2/3 s-1','CITEDR'],
'51':['Visibility Through Precipitation','m','VISPCP'],
table_4_2_0_20  = {
'0':['Mass Density (Concentration)','kg m-3','MASSDEN'],
'1':['Column-Integrated Mass Density','kg m-2','COLMD'],
'2':['Mass Mixing Ratio (Mass Fraction in Air)','kg kg-1','MASSMR'],
'3':['Atmosphere Emission Mass Flux','kg m-2s-1','AEMFLX'],
'4':['Atmosphere Net Production Mass Flux','kg m-2s-1','ANPMFLX'],
'5':['Atmosphere Net Production And Emision Mass Flux','kg m-2s-1','ANPEMFLX'],
'6':['Surface Dry Deposition Mass Flux','kg m-2s-1','SDDMFLX'],
'7':['Surface Wet Deposition Mass Flux','kg m-2s-1','SWDMFLX'],
'8':['Atmosphere Re-Emission Mass Flux','kg m-2s-1','AREMFLX'],
'9':['Wet Deposition by Large-Scale Precipitation Mass Flux','kg m-2s-1','WLSMFLX'],
'10':['Wet Deposition by Convective Precipitation Mass Flux','kg m-2s-1','WDCPMFLX'],
'11':['Sedimentation Mass Flux','kg m-2s-1','SEDMFLX'],
'12':['Dry Deposition Mass Flux','kg m-2s-1','DDMFLX'],
'13':['Transfer From Hydrophobic to Hydrophilic','kg kg-1s-1','TRANHH'],
'14':['Transfer From SO2 (Sulphur Dioxide) to SO4 (Sulphate)','kg kg-1s-1','TRSDS'],
'15':['Dry deposition velocity','m s-1','DDVEL'],
'16':['Mass mixing ratio with respect to dry air','kg kg-1','MSSRDRYA'],
'17':['Mass mixing ratio with respect to wet air','kg kg-1','MSSRWETA'],
'18':['Potential of hydrogen (pH)','pH','POTHPH'],
table_4_2_0_190  = {
'0':['Arbitrary Text String','CCITTIA5','ATEXT'],
table_4_2_0_191  = {
'0':['Seconds prior to initial reference time (defined in Section 1)','s','TSEC'],
'1':['Geographical Latitude','° N','GEOLAT'],
'2':['Geographical Longitude','° E','GEOLON'],
'3':['Days Since Last Observation','d','DSLOBS'],
'4':['Tropical cyclone density track','Numeric','TCDTRACK'],
'5':['Hurricane track in spatiotemporal vicinity','boolean','HURTSV'],
'6':['Tropical storm track in spatiotemporal vicinity','boolean','TSTSV'],
'7':['Tropical depression track in spatiotemporal vicinity','boolean','TDTSV'],
table_4_2_0_192  = {
'1':['Covariance between zonal and meridional components of the wind. Defined as [uv]-[u][v], where "[]" indicates the mean over the indicated time span.','m2/s2','COVMZ'],
'2':['Covariance between zonal component of the wind and temperature. Defined as [uT]-[u][T], where "[]" indicates the mean over the indicated time span.','K*m/s','COVTZ'],
'3':['Covariance between meridional component of the wind and temperature. Defined as [vT]-[v][T], where "[]" indicates the mean over the indicated time span.','K*m/s','COVTM'],
'4':['Covariance between temperature and vertical component of the wind. Defined as [wT]-[w][T], where "[]" indicates the mean over the indicated time span.','K*m/s','COVTW'],
'5':['Covariance between zonal and zonal components of the wind. Defined as [uu]-[u][u], where "[]" indicates the mean over the indicated time span.','m2/s2','COVZZ'],
'6':['Covariance between meridional and meridional components of the wind. Defined as [vv]-[v][v], where "[]" indicates the mean over the indicated time span.','m2/s2','COVMM'],
'7':['Covariance between specific humidity and zonal components of the wind. Defined as [uq]-[u][q], where "[]" indicates the mean over the indicated time span.','kg/kg*m/s','COVQZ'],
'8':['Covariance between specific humidity and meridional components of the wind. Defined as [vq]-[v][q], where "[]" indicates the mean over the indicated time span.','kg/kg*m/s','COVQM'],
'9':['Covariance between temperature and vertical components of the wind. Defined as [ΩT]-[Ω][T], where "[]" indicates the mean over the indicated time span.','K*Pa/s','COVTVV'],
'10':['Covariance between specific humidity and vertical components of the wind. Defined as [Ωq]-[Ω][q], where "[]" indicates the mean over the indicated time span.','kg/kg*Pa/s','COVQVV'],
'11':['Covariance between surface pressure and surface pressure. Defined as [Psfc]-[Psfc][Psfc], where "[]" indicates the mean over the indicated time span.','Pa*Pa','COVPSPS'],
'12':['Covariance between specific humidity and specific humidy. Defined as [qq]-[q][q], where "[]" indicates the mean over the indicated time span.','kg/kg*kg/kg','COVQQ'],
'13':['Covariance between vertical and vertical components of the wind. Defined as [ΩΩ]-[Ω][Ω], where "[]" indicates the mean over the indicated time span.','Pa2/s2','COVVVVV'],
'14':['Covariance between temperature and temperature. Defined as [TT]-[T][T], where "[]" indicates the mean over the indicated time span.','K*K','COVTT'],
# ----------------------------------------------------------------------------------------
# Source: https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/blob/develop/wgrib2/NDFD_gribtab.dat
#         and
#         https://vlab.noaa.gov/web/mdl/ndfd-grib-all-sections#section-4-product-definition-section
#
# The dictionary names are in the following format:
#     table_4_2_<discipline>_<parameterCategory>_ndfd	
# ----------------------------------------------------------------------------------------
table_4_2_0_0_ndfd = {
'193':['Apparent Temperature','K','APPT'],
}

table_4_2_0_1_ndfd = {
'192':['Weather Information','WxInfo','WX'],
}

table_4_2_0_19_ndfd = {
'194':['Convective Hazard Outlook','categorical','CONVOUTLOOK'],
'197':['Probability of Tornado','%','PTORNADO'],
'198':['Probability of Hail','%','PHAIL'],
'199':['Probability of Damaging Wind','%','PWIND'],
'200':['Probability of Extreme Tornado','%','PXTRMTORN'],
'201':['Probability of Extreme Hail','%','PXTRMHAIL'],
'202':['Probability of Extreme Wind','%','PXTRMWIND'],
'215':['Total Probability of Severe Thunderstorms','%','TOTALSVRPROB'],
'216':['Total Probability of Extreme Severe Thunderstorms','%','TOTALXTRMPROB'],
'217':['Watch Warning Advisory','WxInfo','WWA'],
}

table_4_2_0_192_ndfd = {
'192':['Critical Fire Weather','','FIREWX'],
'194':['Dry Lightning','','DRYLIGHTNING'],
}
