table_4_2_3_0  = {
'0':['Scaled Radiance','Numeric','SRAD'],
'1':['Scaled Albedo','Numeric','SALBEDO'],
'2':['Scaled Brightness Temperature','Numeric','SBTMP'],
'3':['Scaled Precipitable Water','Numeric','SPWAT'],
'4':['Scaled Lifted Index','Numeric','SLFTI'],
'5':['Scaled Cloud Top Pressure','Numeric','SCTPRES'],
'6':['Scaled Skin Temperature','Numeric','SSTMP'],
'7':['Cloud Mask','See Table 4.217','CLOUDM'],
'8':['Pixel Scene Type','See Table 4.218','PIXST'],
'9':['Fire Detection Indicator','See Table 4.223','FIREDI'],
table_4_2_3_1  = {
'0':['Estimated Precipitation','kg m-2','ESTP'],
'1':['Instantaneous Rain Rate','kg m-2 s-1','IRRATE'],
'2':['Cloud Top Height','m','CTOPH'],
'3':['Cloud Top Height Quality Indicator','Code table 4.219','CTOPHQI'],
'4':['Estimated U-Component of Wind','m s-1','ESTUGRD'],
'5':['Estimated V-Component of Wind','m s-1','ESTVGRD'],
'6':['Number Of Pixels Used','Numeric','NPIXU'],
'7':['Solar Zenith Angle','°','SOLZA'],
'8':['Relative Azimuth Angle','°','RAZA'],
'9':['Reflectance in 0.6 Micron Channel','%','RFL06'],
'10':['Reflectance in 0.8 Micron Channel','%','RFL08'],
'11':['Reflectance in 1.6 Micron Channel','%','RFL16'],
'12':['Reflectance in 3.9 Micron Channel','%','RFL39'],
'13':['Atmospheric Divergence','s-1','ATMDIV'],
'14':['Cloudy Brightness Temperature','K','CBTMP'],
'15':['Clear Sky Brightness Temperature','K','CSBTMP'],
table_4_2_3_2  = {
'0':['Clear Sky Probability','%','CSKPROB'],
'1':['Cloud Top Temperature','K','CTOPTMP'],
'2':['Cloud Top Pressure','Pa','CTOPRES'],
'3':['Cloud Type','See Table 4.218','CLDTYPE'],
'4':['Cloud Phase','See Table 4.218','CLDPHAS'],
'5':['Cloud Optical Depth','Numeric','CLDODEP'],
'6':['Cloud Particle Effective Radius','m','CLDPER'],
'7':['Cloud Liquid Water Path','kg m-2','CLDLWP'],
'8':['Cloud Ice Water Path','kg m-2','CLDIWP'],
'9':['Cloud Albedo','Numeric','CLDALB'],
'10':['Cloud Emissivity','Numeric','CLDEMISS'],
'11':['Effective Absorption Optical Depth Ratio','Numeric','EAODR'],
table_4_2_3_3  = {
'0':['Probability of Encountering Marginal Visual Flight Rules Conditions','%','PBMVFRC'],
'1':['Probability of Encountering Low Instrument Flight Rules Conditions','%','PBLIFRC'],
'2':['Probability of Encountering Instrument Flight Rules Conditions','%','PBINFRC'],
table_4_2_3_4  = {
'0':['Volcanic Ash Probability','%','VOLAPROB'],
'1':['Volcanic Ash Cloud Top Temperature','K','VOLACDTT'],
'2':['Volcanic Ash Cloud Top Pressure','Pa','VOLACDTP'],
'3':['Volcanic Ash Cloud Top Height','m','VOLACDTH'],
'4':['Volcanic Ash Cloud Emissity','Numeric','VOLACDEM'],
'5':['Volcanic Ash Effective Absorption Depth Ratio','Numeric','VOLAEADR'],
'6':['Volcanic Ash Cloud Optical Depth','Numeric','VOLACDOD'],
'7':['Volcanic Ash Column Density','kg m-2','VOLACDEN'],
'8':['Volcanic Ash Particle Effective Radius','m','VOLAPER'],
table_4_2_3_5  = {
'0':['Interface Sea Surface Temperature','K','ISSTMP'],
'1':['Skin Sea Surface Temperature','K','SKSSTMP'],
'2':['Sub-Skin Sea Surface Temperature','K','SSKSSTMP'],
'3':['Foundation Sea Surface Temperature','K','FDNSSTMP'],
'4':['Estimated bias between Sea Surface Temperature and Standard','K','EBSSTSTD'],
'5':['Estimated bias Standard Deviation between Sea Surface Temperature and Standard','K','EBSDSSTS'],
table_4_2_3_6  = {
'0':['Global Solar Irradiance','W m-2','GSOLIRR'],
'1':['Global Solar Exposure','J m-2','GSOLEXP'],
'2':['Direct Solar Irradiance','W m-2','DIRSOLIR'],
'3':['Direct Solar Exposure','J m-2','DIRSOLEX'],
'4':['Diffuse Solar Irradiance','W m-2','DIFSOLIR'],
'5':['Diffuse Solar Exposure','J m-2','DIFSOLEX'],
table_4_2_3_192  = {
'0':['Simulated Brightness Temperature for GOES 12, Channel 2','K','SBT122'],
'1':['Simulated Brightness Temperature for GOES 12, Channel 3','K','SBT123'],
'2':['Simulated Brightness Temperature for GOES 12, Channel 4','K','SBT124'],
'3':['Simulated Brightness Temperature for GOES 12, Channel 6','K','SBT126'],
'4':['Simulated Brightness Counts for GOES 12, Channel 3','Byte','SBC123'],
'5':['Simulated Brightness Counts for GOES 12, Channel 4','Byte','SBC124'],
'6':['Simulated Brightness Temperature for GOES 11, Channel 2','K','SBT112'],
'7':['Simulated Brightness Temperature for GOES 11, Channel 3','K','SBT113'],
'8':['Simulated Brightness Temperature for GOES 11, Channel 4','K','SBT114'],
'9':['Simulated Brightness Temperature for GOES 11, Channel 5','K','SBT115'],
'10':['Simulated Brightness Temperature for AMSRE on Aqua, Channel 9','K','AMSRE9'],
'11':['Simulated Brightness Temperature for AMSRE on Aqua, Channel 10','K','AMSRE10'],
'12':['Simulated Brightness Temperature for AMSRE on Aqua, Channel 11','K','AMSRE11'],
'13':['Simulated Brightness Temperature for AMSRE on Aqua, Channel 12','K','AMSRE12'],
