table_4_2_20_0  = {
'0':['Universal Thermal Climate Index','K','UTHCIDX'],
'1':['Mean Radiant Temperature','K','MEANRTMP'],
'2':['Wet-bulb Globe Temperature (see Note)','K','WETBGTMP'],
'3':['Globe Temperature (see Note)','K','GLOBETMP'],
'4':['Humidex','K','HUMIDX'],
'5':['Effective Temperature','K','EFFTEMP'],
'6':['Normal Effective Temperature','K','NOREFTMP'],
'7':['Standard Effective Temperature','K','STDEFTMP'],
'8':['Physiological Equivalent Temperature','K','PEQUTMP'],
'9-191':['Reserved','unknown','unknown'],
'192-254':['Reserved for Local Use','unknown','unknown'],
'255':['Missing','unknown','unknown'],
}
table_4_2_20_1  = {
'0':['Malaria Cases','Fraction','MALACASE'],
'1':['Malaria Circumsporozoite Protein Rate','Fraction','MACPRATE'],
'2':['Plasmodium Falciparum Entomological Inoculation Rate','Bites per day per person','PFEIRATE'],
'3':['Human Bite Rate by Anopheles Vectors','Bites per day per person','HBRATEAV'],
'4':['Malaria Immunity','Fraction','MALAIMM'],
'5':['Falciparum Parasite Rates','Fraction','FALPRATE'],
'6':['Detectable Falciparum Parasite Ratio (after day 10)','Fraction','DFPRATIO'],
'7':['Anopheles Vector to Host Ratio','Fraction','AVHRATIO'],
'8':['Anopheles Vector Number','Number m-2','AVECTNUM'],
'9':['Fraction of Malarial Vector Reproductive Habitat','Fraction','FMALVRH'],
'10-191':['Reserved','unknown','unknown'],
'192-254':['Reserved for Local Use','unknown','unknown'],
'255':['Missing','unknown','unknown'],
}
table_4_2_20_2  = {
'0':['Population Density','Person m-2','POPDEN'],
'1-191':['Reserved','unknown','unknown'],
'192-254':['Reserved for Local Use','unknown','unknown'],
'255':['Missing','unknown','unknown'],
}
