table_4_2_2_0  = {
'0':['Land Cover (0=sea, 1=land)','Proportion','LAND'],
'1':['Surface Roughness','m','SFCR'],
'2':['Soil Temperature','K','TSOIL'],
table_4_2_2_1  = {
table_4_2_2_3  = {
'0':['Soil Type','See Table 4.213','SOTYP'],
'1':['Upper Layer Soil Temperature','K','UPLST'],
'2':['Upper Layer Soil Moisture','kg m-3','UPLSM'],
'3':['Lower Layer Soil Moisture','kg m-3','LOWLSM'],
'4':['Bottom Layer Soil Temperature','K','BOTLST'],
'5':['Liquid Volumetric Soil Moisture (non-frozen)','Proportion','SOILL'],
'6':['Number of Soil Layers in Root Zone','Numeric','RLYRS'],
'7':['Transpiration Stress-Onset (Soil Moisture)','Proportion','SMREF'],
'8':['Direct Evaporation Cease (Soil Moisture)','Proportion','SMDRY'],
'9':['Soil Porosity','Proportion','POROS'],
'10':['Liquid Volumetric Soil Moisture (Non-Frozen)','m3 m-3','LIQVSM'],
'11':['Volumetric Transpiration Stress-Onset (Soil Moisture)','m3 m-3','VOLTSO'],
'12':['Transpiration Stress-Onset (Soil Moisture)','kg m-3','TRANSO'],
'13':['Volumetric Direct Evaporation Cease (Soil Moisture)','m3 m-3','VOLDEC'],
'14':['Direct Evaporation Cease (Soil Moisture)','kg m-3','DIREC'],
'15':['Soil Porosity','m3 m-3','SOILP'],
'16':['Volumetric Saturation Of Soil Moisture','m3 m-3','VSOSM'],
'17':['Saturation Of Soil Moisture','kg m-3','SATOSM'],
'18':['Soil Temperature','K','SOILTMP'],
'19':['Soil Moisture','kg m-3','SOILMOI'],
'20':['Column-Integrated Soil Moisture','kg m-2','CISOILM'],
'21':['Soil Ice','kg m-3','SOILICE'],
'22':['Column-Integrated Soil Ice','kg m-2','CISICE'],
'23':['Liquid Water in Snow Pack','kg m-2','LWSNWP'],
'24':['Frost Index','kg day-1','FRSTINX'],
'25':['Snow Depth at Elevation Bands','kg m-2','SNWDEB'],
'26':['Soil Heat Flux','W m-2','SHFLX'],
'27':['Soil Depth','m','SOILDEP'],
'28':['Snow Temperature','K','SNOWTMP'],
'29':['Ice Temperature','K','ICETEMP'],
'30':['Soil Wetness Index','Numeric','SWET'],
table_4_2_2_4  = {
'0':['Fire Outlook','See Table 4.224','FIREOLK'],
'1':['Fire Outlook Due to Dry Thunderstorm','See Table 4.224','FIREODT'],
'2':['Haines Index','Numeric','HINDEX'],
'3':['Fire Burned Area','%','FBAREA'],
'4':['Fosberg Index','Numeric','FOSINDX'],
'5':['Forest Fire Weather Index (as defined by the Canadian Forest Service)','Numeric','FWINX'],
'6':['Fine Fuel Moisture Code (as defined by the Canadian Forest Service)','Numeric','FFMCODE'],
'7':['Duff Moisture Code (as defined by the Canadian Forest Service)','Numeric','DUFMCODE'],
'8':['Drought Code (as defined by the Canadian Forest Service)','Numeric','DRTCODE'],
'9':['Initial Fire Spread Index (as defined by the Canadian Forest Service)','Numeric','INFSINX'],
'10':['Fire Buildup Index (as defined by the Canadian Forest Service)','Numeric','FBUPINX'],
'11':['Fire Daily Severity Rating (as defined by the Canadian Forest Service)','Numeric','FDSRTE'],
'12':['Keetch-Byram Drought Index','Numeric','KRIDX'],
'13':['Drought Factor (as defined by the Australian Forest Service)','Numeric','DRFACT'],
'14':['Rate of Spread (as defined by the Australian Forest Service)','m s-1','RATESPRD'],
'15':['Fire Danger index (as defined by the Australian Forest Service)','Numeric','FIREDIDX'],
'16':['Spread Component (as defined by the US Forest Service National Fire Danger Rating System)','Numeric','SPRDCOMP'],
'17':['Burning Index (as defined by the US Forest Service National Fire Danger Rating System)','Numeric','BURNIDX'],
'18':['Ignition Component (as defined by the US Forest Service National Fire Danger Rating System)','%','IGNCOMP'],
'19':['Energy Release Component (as defined by the US Forest Service National Fire Danger Rating System)','J m-2','ENRELCOM'],
'20':['Burning Area','%','BURNAREA'],
'21':['Burnable Area','%','BURNABAREA'],
'22':['Unburnable Area','%','UNBURNAREA'],
'23':['Fuel Load','kg m-2','FUELLOAD'],
'24':['Combustion Completeness','%','COMBCO'],
'25':['Fuel Moisture Content','kg kg-1','FUELMC'],
'26':['Wildfire Potential (as defined by the US NOAA Global Systems Laboratory)','Numeric','WFIREPOT'],
'27':['Live Leaf Fuel Load','kg m-2','LLFL'],
'28':['Live Wood Fuel Load','kg m-2','LWFL'],
'29':['Dead Leaf Fuel Load','kg m-2','DLFL'],
'30':['Dead Wood Fuel Load','kg m-2','DWFL'],
'31':['Live Fuel Moisture Content','kg kg-1','LFMC'],
'32':['Fine Dead Leaf Moisture Content','kg kg-1','FDLMC'],
'33':['Dense Dead Leaf Moisture Content','kg kg-1','DDLMC'],
'34':['Fine Dead Wood Moisture Content','kg kg-1','FDWMC'],
'35':['Dense Dead Wood Moisture Content','kg kg-1','DDWMC'],
'36':['Fire Radiative Power','W','FRADPOW'],
'37':['Live Fuel Moisture Content in Low Vegetation','kg kg-1','LFMCLV'],
'38':['Live Fuel Moisture Content in High Vegetation','kg kg-1','LFMCHV'],
'39':['Mean Height of Maximum Injection','m','MEANHGTINJ'],
'40':['Injection Height','m','HGTINJ'],
'41':['Plume Bottom Height','m','HGTPLUMEB'],
'42':['Plume Top Height','m','HGTPLUMET'],
table_4_2_2_5  = {
'0':['Glacier Cover','Proportion','GLACCOV'],
'1':['Glacier Temperature','K','GLACTMP'],
