name: grib2io
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipython
  - dask
  - nceplibs-g2c
  - xarray>=2023.04.0
  - pip:
    - numpy
    - cython
    - pyproj
