table_4_1_0 = {
'0':'Temperature',
'1':'Moisture',
'2':'Momentum',
'3':'Mass',
'4':'Short-wave radiation',
'5':'Long-wave radiation',
'6':'Cloud',
'7':'Thermodynamic Stability indicies',
'8':'Kinematic Stability indicies',
'9':'Temperature Probabilities*',
'10':'Moisture Probabilities*',
'11':'Momentum Probabilities*',
'12':'Mass Probabilities*',
'13':'Aerosols',
'14':'Trace gases',
'15':'Radar',
'16':'Forecast Radar Imagery',
'17':'Electrodynamics',
'18':'Nuclear/radiology',
'19':'Physical atmospheric properties',
'20':'Atmospheric chemical Constituents',
'21':'Thermodynamic Properties',
'22-189':'Reserved',
'190':'CCITT IA5 string',
'191':'Miscellaneous',
'192-254':'Reserved for Local Use',
'192':'Covariance',
'255':'Missing',
}

table_4_1_1 = {
'0':'Hydrology basic products',
'1':'Hydrology probabilities',
'2':'Inland water and sediment properties',
'3-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_1_2 = {
'0':'Vegetation/Biomass',
'1':'Agricultural/Aquacultural Special Products',
'2':'Transportation-related Products',
'3':'Soil Products',
'4':'Fire Weather Products',
'5':'Land Surface Products',
'6':'Urban areas',
'7-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_1_3 = {
'0':'Image format products',
'1':'Quantitative products',
'2':'Cloud Properties',
'3':'Flight Rules Conditions',
'4':'Volcanic Ash',
'5':'Sea-surface Temperature',
'6':'Solar Radiation',
'7-191':'Reserved',
'192-254':'Reserved for Local Use',
'192':'Forecast Satellite Imagery',
'255':'Missing',
}

table_4_1_4 = {
'0':'Temperature',
'1':'Momentum',
'2':'Charged Particle Mass and Number',
'3':'Electric and Magnetic Fields',
'4':'Energetic Particles',
'5':'Waves',
'6':'Solar Electromagnetic Emissions',
'7':'Terrestrial Electromagnetic Emissions',
'8':'Imagery',
'9':'Ion-Neutral Coupling',
'10':'Space Weather Indices',
'11-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_1_10 = {
'0':'Waves',
'1':'Currents',
'2':'Ice',
'3':'Surface Properties',
'4':'Sub-surface Properties',
'5-190':'Reserved',
'191':'Miscellaneous',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_1_20 = {
'0':'Health Indicators',
'1':'Epidemiology',
'2':'Socioeconomic indicators',
'3':'Renewable energy sector',
'4-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_0 = {
'0':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time. (see Template 4.0)',
'1':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time. (see Template 4.1)',
'2':'Derived forecasts based on all ensemble members at a horizontal level or in a horizontal layer at a point in time. (see Template 4.2)',
'3':'Derived forecasts based on a cluster of ensemble members over a rectangular area at a horizontal level or in a horizontal layer at a point in time. (see Template 4.3)',
'4':'Derived forecasts based on a cluster of ensemble members over a circular area at a horizontal level or in a horizontal layer at a point in time. (see Template 4.4)',
'5':'Probability forecasts at a horizontal level or in a horizontal layer at a point in time. (see Template 4.5)',
'6':'Percentile forecasts at a horizontal level or in a horizontal layer at a point in time. (see Template 4.6)',
'7':'Analysis or forecast error at a horizontal level or in a horizontal layer at a point in time. (see Template 4.7)',
'8':'Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval. (see Template 4.8)',
'9':'Probability forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval. (see Template 4.9)',
'10':'Percentile forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval. (see Template 4.10)',
'11':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval. (see Template 4.11)',
'12':'Derived forecasts based on all ensemble members at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval. (see Template 4.12)',
'13':'Derived forecasts based on a cluster of ensemble members over a rectangular area at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval. (see Template 4.13)',
'14':'Derived forecasts based on a cluster of ensemble members over a circular area at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval. (see Template 4.14)',
'15':'Average, accumulation, extreme values or other statistically-processed values over a spatial area at a horizontal level or in a horizontal layer at a point in time. (see Template 4.15)',
'16-19':'Reserved',
'20':'Radar product (see Template 4.20)',
'21-29':'Reserved',
'30':'Satellite product (see Template 4.30) NOTE: This template is deprecated. Template 4.31 should be used instead.',
'31':'Satellite product (see Template 4.31)',
'32':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for simulate (synthetic) satellite data (see Template 4.32)',
'33':'Individual Ensemble Forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for simulated (synthetic) satellite data (see Template 4.33)',
'34':'Individual Ensemble Forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval for simulated (synthetic) satellite data(see Template 4.34)',
'35':'Satellite product with or without associated quality values (see Template 4.35)',
'36-39':'Reserved',
'40':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents. (see Template 4.40)',
'41':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents. (see Template 4.41)',
'42':'Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents. (see Template 4.42)',
'43':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for atmospheric chemical constituents. (see Template 4.43)',
'44':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol. (see Template 4.44)',
'45':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for aerosol. (see Template 4.45)',
'46':'Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for aerosol. (see Template 4.46)',
'47':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for aerosol. (see Template 4.47)',
'48':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol. (see Template 4.48)',
'49':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol. (see Template 4.49)',
'50':'Reserved',
'51':'Categorical forecast at a horizontal level or in a horizontal layer at a point in time. (see Template 4.51)',
'52':'Reserved',
'53':'Partitioned parameters at a horizontal level or horizontal layer at a point in time. (see Template 4.53)',
'54':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for partitioned parameters. (see Template 4.54)',
'55':'Spatio-temporal changing tiles at a horizontal level or horizontal layer at a point in time (see Template 4.55)',
'56':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for spatio-temporal changing tile parameters (DEPRECATED) (see Template 4.56)',
'57':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents based on a distribution function (see Template 4.57)',
'58':'Individual Ensemble Forecast, Control and Perturbed, at a horizontal level or in a horizontal layer at a point in time interval for Atmospheric Chemical Constituents based on a distribution function (see Template 4.58)',
'59':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for spatio-temporal changing tile parameters (corrected version of template 4.56 - See Template 4.59)',
'60':'Individual Ensemble Reforecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time. (see Template 4.60)',
'61':'Individual Ensemble Reforecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval (see Template 4.61)',
'62':'Average, Accumulation and/or Extreme values or other Statistically-processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles at a horizontal level or horizontal layer at a point in time (see Template 4.62)',
'63':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles (see Template 4.63)',
'64-66':'Reserved',
'67':'Average, accumulation and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents based on a distribution function (see Template 4.67)',
'68':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents based on a distribution function. (see Template 4.68)',
'69':'Reserved',
'70':'Post-processing analysis or forecast at a horizontal level or in a horizontal layer at a point in time. (see Template 4.70)',
'71':'Post-processing individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time. (see Template 4.71)',
'72':'Post-processing average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval. (see Template 4.72)',
'73':'Post-processing individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval. (see Template 4.73)',
'74-75':'Reserved',
'76':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents with source or sink. (see Template 4.76)',
'77':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents with source or sink. (see Template 4.77)',
'78':'Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents with source or sink. (see Template 4.78)',
'79':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents with source or sink. (see Template 4.79)',
'80':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol with source or sink. (see Template 4.80)',
'81':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol with source or sink. (see Template 4.81)',
'82':'Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for aerosol with source or sink. (see Template 4.82)',
'83':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for aerosol with source or sink. (see Template 4.83)',
'84':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for aerosol with source or sink. (see Template 4.84)',
'85':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for aerosol. (see Template 4.85)',
'86':'Quantile forecasts at a horizontal level or in a horizontal layer at a point in time. (see Template 4.86)',
'87':'Quantile forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval. (see Template 4.87)',
'88':'Analysis or forecast at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.88)',
'89-90':'Reserved',
'91':'Categorical forecast at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval. (see Template 4.91)',
'92':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.92)',
'93':'Post-processing analysis or forecast at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.93)',
'94':'Post-processing individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.94)',
'95':'Average, accumulation, extreme values or other statiscally processed value at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.95)',
'96':'Average, accumulation, extreme values or other statistically processed values of an individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.96)',
'97':'Average, accumulation, extreme values or other statistically processed values of post-processing analysis or forecast at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.97)',
'98':'Average, accumulation, extreme values or other statistically processed values of a post-processing individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a specified local time. (see Template 4.98)',
'99':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for wave 2D spectra with explicit list of frequencies and directions (see Template 4.99)',
'100':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for wave 2D spectra with explicit list of frequencies and directions (see Template 4.100)',
'101':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for wave 2D spectra with frequencies and directions defined by formulae (see Template 4.101)',
'102':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for wave 2D spectra with frequencies and directions defined by formulae (see Template 4.102)',
'103':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for waves selected by period range (see Template 4.103)',
'104':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for waves selected by period range (see Template 4.104)',
'105':'Anomalies, significance and other derived products from an analysis or forecast in relation to a reference period at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval (see Template 4.105)',
'106':'Anomalies, significance and other derived products from an individual ensemble forecast, control and perturbed in relation to a reference period at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval (see Template 4.106)',
'107':'Anomalies, significance and other derived products from derived forecasts based on all ensemble members in relation to a reference period at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval (see Template 4.107)',
'108':'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for generic optical products (see Template 4.108)',
'109':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for generic optical products (see Template 4.109)',
'110':'Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for generic optical products (see Template 4.110)',
'111':'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval for generic optical products (see Template 4.111)',
'112':'Anomalies, significance and other derived products as probability forecasts in relation to a reference period at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval (see Template 4.112)',
'113-253':'Reserved',
'254':'CCITT IA5 character string (see Template 4.254)',
'255-999':'Reserved',
'1000':'Cross-section of analysis and forecast at a point in time. (see Template 4.1000)',
'1001':'Cross-section of averaged or otherwise statistically processed analysis or forecast over a range of time. (see Template 4.1001)',
'1002':'Cross-section of analysis and forecast, averaged or otherwise statistically-processed over latitude or longitude. (see Template 4.1002)',
'1003-1099':'Reserved',
'1100':'Hovmoller-type grid with no averaging or other statistical processing (see Template 4.1100)',
'1101':'Hovmoller-type grid with averaging or other statistical processing (see Template 4.1101)',
'1102-32767':'Reserved',
'32768-65534':'Reserved for Local Use',
'65535':'Missing',
}

table_4_3 = {
'0':'Analysis',
'1':'Initialization',
'2':'Forecast',
'3':'Bias Corrected Forecast',
'4':'Ensemble Forecast',
'5':'Probability Forecast',
'6':'Forecast Error',
'7':'Analysis Error',
'8':'Observation',
'9':'Climatological',
'10':'Probability-Weighted Forecast',
'11':'Bias-Corrected Ensemble Forecast',
'12':'Post-processed Analysis (See Note)',
'13':'Post-processed Forecast (See Note)',
'14':'Nowcast',
'15':'Hindcast',
'16':'Physical Retrieval',
'17':'Regression Analysis',
'18':'Difference Between Two Forecasts',
'19':'First guess',
'20':'Analysis increment',
'21':'Initialization increment for analysis',
'22-191':'Reserved',
'192-254':'Reserved for Local Use',
'192':'Forecast Confidence Indicator',
'193':'Probability-matched Mean',
'194':'Neighborhood Probability',
'195':'Bias-Corrected and Downscaled Ensemble Forecast',
'196':'Perturbed Analysis for Ensemble Initialization',
'197':'Ensemble Agreement Scale Probability',
'198':'Post-Processed Deterministic-Expert-Weighted Forecast',
'199':'Ensemble Forecast Based on Counting',
'200':'Local Probability-matched Mean',
'255':'Missing',
}

table_4_4 = {
'0':'Minute',
'1':'Hour',
'2':'Day',
'3':'Month',
'4':'Year',
'5':'Decade (10 Years)',
'6':'Normal (30 Years)',
'7':'Century (100 Years)',
'8':'Reserved',
'9':'Reserved',
'10':'3 Hours',
'11':'6 Hours',
'12':'12 Hours',
'13':'Second',
'14-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_5 = {
'0':['Reserved','unknown'],
'1':['Ground or Water Surface','unknown'],
'2':['Cloud Base Level','unknown'],
'3':['Level of Cloud Tops','unknown'],
'4':['Level of 0o C Isotherm','unknown'],
'5':['Level of Adiabatic Condensation Lifted from the Surface','unknown'],
'6':['Maximum Wind Level','unknown'],
'7':['Tropopause','unknown'],
'8':['Nominal Top of the Atmosphere','unknown'],
'9':['Sea Bottom','unknown'],
'10':['Entire Atmosphere','unknown'],
'11':['Cumulonimbus Base (CB)','m'],
'12':['Cumulonimbus Top (CT)','m'],
'13':['Lowest level where vertically integrated cloud cover exceeds the specified percentage (cloud base for a given percentage cloud cover)','%'],
'14':['Level of free convection (LFC)','unknown'],
'15':['Convection condensation level (CCL)','unknown'],
'16':['Level of neutral buoyancy or equilibrium (LNB)','unknown'],
'17':['Departure level of the most unstable parcel of air (MUDL)','unknown'],
'18':['Departure level of a mixed layer parcel of air with specified layer depth','Pa'],
'19':['Reserved','unknown'],
'20':['Isothermal Level','K'],
'21':['Lowest level where mass density exceeds the specified value (base for a given threshold of mass density)','kg m-3'],
'22':['Highest level where mass density exceeds the specified value (top for a given threshold of mass density)','kg m-3'],
'23':['Lowest level where air concentration exceeds the specified value (base for a given threshold of air concentration','Bq m-3'],
'24':['Highest level where air concentration exceeds the specified value (top for a given threshold of air concentration)','Bq m-3'],
'25':['Highest level where radar reflectivity exceeds the specified value (echo top for a given threshold of reflectivity)','dBZ'],
'26':['Convective cloud layer base','m'],
'27':['Convective cloud layer top','m'],
'28-29':['Reserved','unknown'],
'30':['Specified radius from the centre of the Sun','m'],
'31':['Solar photosphere','unknown'],
'32':['Ionospheric D-region level','unknown'],
'33':['Ionospheric E-region level','unknown'],
'34':['Ionospheric F1-region level','unknown'],
'35':['Ionospheric F2-region level','unknown'],
'36-99':['Reserved','unknown'],
'100':['Isobaric Surface','Pa'],
'101':['Mean Sea Level','unknown'],
'102':['Specific Altitude Above Mean Sea Level','m'],
'103':['Specified Height Level Above Ground','m'],
'104':['Sigma Level','unknown'],
'105':['Hybrid Level','unknown'],
'106':['Depth Below Land Surface','m'],
'107':['Isentropic (theta) Level','K'],
'108':['Level at Specified Pressure Difference from Ground to Level','Pa'],
'109':['Potential Vorticity Surface','K m2 kg-1 s-1'],
'110':['Reserved','unknown'],
'111':['Eta Level','unknown'],
'112':['Reserved','unknown'],
'113':['Logarithmic Hybrid Level','unknown'],
'114':['Snow Level','Numeric'],
'115':['Sigma height level','unknown'],
'116':['Reserved','unknown'],
'117':['Mixed Layer Depth','m'],
'118':['Hybrid Height Level','unknown'],
'119':['Hybrid Pressure Level','unknown'],
'120-149':['Reserved','unknown'],
'150':['Generalized Vertical Height Coordinate','unknown'],
'151':['Soil level','Numeric'],
'152':['Sea-ice level,(see Note 8)','Numeric'],
'153-159':['Reserved','unknown'],
'160':['Depth Below Sea Level','m'],
'161':['Depth Below Water Surface','m'],
'162':['Lake or River Bottom','unknown'],
'163':['Bottom Of Sediment Layer','unknown'],
'164':['Bottom Of Thermally Active Sediment Layer','unknown'],
'165':['Bottom Of Sediment Layer Penetrated By Thermal Wave','unknown'],
'166':['Mixing Layer','unknown'],
'167':['Bottom of Root Zone','unknown'],
'168':['Ocean Model Level','Numeric'],
'169':['Ocean level defined by water density (sigma-theta) difference from near-surface to level','kg m-3'],
'170':['Ocean level defined by water potential temperature difference from near-surface to level','K'],
'171':['Ocean level defined by vertical eddy diffusivity difference from near-surface to level','m2 s-1'],
'172':['Ocean level defined by water density (rho) difference from near-surface to level (*Tentatively accepted)','kg m-3'],
'173':['Top of Snow Over Sea Ice on Sea, Lake or River','unknown'],
'174':['Top Surface of Ice on Sea, Lake or River','unknown'],
'175':['Top Surface of Ice, under Snow, on Sea, Lake or River','unknown'],
'176':['Bottom Surface (underside) Ice on Sea, Lake or River','unknown'],
'177':['Deep Soil (of indefinite depth)','unknown'],
'178':['Reserved','unknown'],
'179':['Top Surface of Glacier Ice and Inland Ice','unknown'],
'180':['Deep Inland or Glacier Ice (of indefinite depth)','unknown'],
'181':['Grid Tile Land Fraction as a Model Surface','unknown'],
'182':['Grid Tile Water Fraction as a Model Surface','unknown'],
'183':['Grid Tile Ice Fraction on Sea, Lake or River as a Model Surface','unknown'],
'184':['Grid Tile Glacier Ice and Inland Ice Fraction as a Model Surface','unknown'],
'185':['Roof Level','unknown'],
'186':['Wall level','unknown'],
'187':['Road Level','unknown'],
'188':['Melt pond Top Surface','unknown'],
'189':['Melt Pond Bottom Surface','unknown'],
'190-191':['Reserved','unknown'],
'192-254':['Reserved for Local Use','unknown'],
'200':['Entire atmosphere (considered as a single layer)','unknown'],
'201':['Entire ocean (considered as a single layer)','unknown'],
'204':['Highest tropospheric freezing level','unknown'],
'206':['Grid scale cloud bottom level','unknown'],
'207':['Grid scale cloud top level','unknown'],
'209':['Boundary layer cloud bottom level','unknown'],
'210':['Boundary layer cloud top level','unknown'],
'211':['Boundary layer cloud layer','unknown'],
'212':['Low cloud bottom level','unknown'],
'213':['Low cloud top level','unknown'],
'214':['Low cloud layer','unknown'],
'215':['Cloud ceiling','unknown'],
'216':['Effective Layer Top Level','m'],
'217':['Effective Layer Bottom Level','m'],
'218':['Effective Layer','m'],
'220':['Planetary Boundary Layer','unknown'],
'221':['Layer Between Two Hybrid Levels','unknown'],
'222':['Middle cloud bottom level','unknown'],
'223':['Middle cloud top level','unknown'],
'224':['Middle cloud layer','unknown'],
'232':['High cloud bottom level','unknown'],
'233':['High cloud top level','unknown'],
'234':['High cloud layer','unknown'],
'235':['Ocean Isotherm Level (1/10 ° C)','unknown'],
'236':['Layer between two depths below ocean surface','unknown'],
'237':['Bottom of Ocean Mixed Layer (m)','unknown'],
'238':['Bottom of Ocean Isothermal Layer (m)','unknown'],
'239':['Layer Ocean Surface and 26C Ocean Isothermal Level','unknown'],
'240':['Ocean Mixed Layer','unknown'],
'241':['Ordered Sequence of Data','unknown'],
'242':['Convective cloud bottom level','unknown'],
'243':['Convective cloud top level','unknown'],
'244':['Convective cloud layer','unknown'],
'245':['Lowest level of the wet bulb zero','unknown'],
'246':['Maximum equivalent potential temperature level','unknown'],
'247':['Equilibrium level','unknown'],
'248':['Shallow convective cloud bottom level','unknown'],
'249':['Shallow convective cloud top level','unknown'],
'251':['Deep convective cloud bottom level','unknown'],
'252':['Deep convective cloud top level','unknown'],
'253':['Lowest bottom level of supercooled liquid water layer','unknown'],
'254':['Highest top level of supercooled liquid water layer','unknown'],
'255':['Missing','unknown'],
}

table_4_6 = {
'0':'Unperturbed High-Resolution Control Forecast',
'1':'Unperturbed Low-Resolution Control Forecast',
'2':'Negatively Perturbed Forecast',
'3':'Positively Perturbed Forecast',
'4':'Multi-Model Forecast',
'5-191':'Reserved',
'192-254':'Reserved for Local Use',
'192':'Perturbed Ensemble Member',
'255':'Missing',
}

table_4_7 = {
'0':'Unweighted Mean of All Members',
'1':'Weighted Mean of All Members',
'2':'Standard Deviation with respect to Cluster Mean',
'3':'Standard Deviation with respect to Cluster Mean, Normalized',
'4':'Spread of All Members',
'5':'Large Anomaly Index of All Members',
'6':'Unweighted Mean of the Cluster Members',
'7':'Interquartile Range (Range between the 25th and 75th quantile)',
'8':'Minimum Of All Ensemble Members',
'9':'Maximum Of All Ensemble Members',
'10-191':'Reserved',
'192-254':'Reserved for Local Use',
'192':'Unweighted Mode of All Members',
'193':'Percentile value (10%) of All Members',
'194':'Percentile value (50%) of All Members',
'195':'Percentile value (90%) of All Members',
'196':'Statistically decided weights for each ensemble member',
'197':'Climate Percentile (percentile values from climate distribution)',
'198':'Deviation of Ensemble Mean from Daily Climatology',
'199':'Extreme Forecast Index',
'200':'Equally Weighted Mean',
'201':'Percentile value (5%) of All Members',
'202':'Percentile value (25%) of All Members',
'203':'Percentile value (75%) of All Members',
'204':'Percentile value (95%) of All Members',
'255':'Missing',
}

table_4_8 = {
'0':'Anomoly Correlation',
'1':'Root Mean Square',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_9 = {
'0':'Probability of event below lower limit',
'1':'Probability of event above upper limit',
'2':'Probability of event between upper and lower limits (the range includes lower limit but no the upper limit)',
'3':'Probability of event above lower limit',
'4':'Probability of event below upper limit',
'5':'Probability of event equal to lower limit',
'6':'Probability of event in above normal category (see Notes 1 and 2)',
'9-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_10 = {
'0':'Average',
'1':'Accumulation',
'2':'Maximum',
'3':'Minimum',
'4':'Difference (value at the end of the time range minus value at the beginning)',
'5':'Root Mean Square',
'6':'Standard Deviation',
'7':'Covariance (temporal variance)',
'8':'Difference ( value at the beginning of the time range minus value at the end)',
'9':'Ratio',
'10':'Standardized Anomaly',
'11':'Summation',
'12':'Return period',
'13-99':'Reserved',
'100':'Severity',
'101':'Mode',
'102-191':'Reserved',
'192-254':'Reserved for Local Use',
'192':'Climatological Mean Value: multiple year averages of quantities which are themselves means over some period of time (P2) less than a year. The reference time (R) indicates the date and time of the start of a period of time, given by R to R + P2, over which a mean is formed; N indicates the number of such period-means that are averaged together to form the climatological value, assuming that the N period-mean fields are separated by one year. The reference time indicates the start of the N-year climatology. N is given in octets 22-23 of the PDS. If P1 = 0 then the data averaged in the basic interval P2 are assumed to be continuous, i.e., all available data are simply averaged together. If P1 = 1 (the units of time - octet 18, code table 4 - are not relevant here) then the data averaged together in the basic interval P2 are valid only at the time (hour, minute) given in the reference time, for all the days included in the P2 period. The units of P2 are given by the contents of octet 18 and Table 4.',
'193':'Average of N forecasts (or initialized analyses); each product has forecast period of P1 (P1=0 for initialized analyses); products have reference times at intervals of P2, beginning at the given reference time.',
'194':'Average of N uninitialized analyses, starting at reference time, at intervals of P2.',
'195':'Average of forecast accumulations. P1 = start of accumulation period. P2 = end of accumulation period. Reference time is the start time of the first forecast, other forecasts at 24-hour intervals. Number in Ave = number of forecasts used.',
'196':'Average of successive forecast accumulations. P1 = start of accumulation period. P2 = end of accumulation period. Reference time is the start time of the first forecast, other forecasts at (P2 - P1) intervals. Number in Ave = number of forecasts used',
'197':'Average of forecast averages. P1 = start of averaging period. P2 = end of averaging period. Reference time is the start time of the first forecast, other forecasts at 24-hour intervals. Number in Ave = number of forecast used',
'198':'Average of successive forecast averages. P1 = start of averaging period. P2 = end of averaging period. Reference time is the start time of the first forecast, other forecasts at (P2 - P1) intervals. Number in Ave = number of forecasts used',
'199':'Climatological Average of N analyses, each a year apart, starting from initial time R and for the period from R+P1 to R+P2.',
'200':'Climatological Average of N forecasts, each a year apart, starting from initial time R and for the period from R+P1 to R+P2.',
'201':'Climatological Root Mean Square difference between N forecasts and their verifying analyses, each a year apart, starting with initial time R and for the period from R+P1 to R+P2.',
'202':'Climatological Standard Deviation of N forecasts from the mean of the same N forecasts, for forecasts one year apart. The first forecast starts wtih initial time R and is for the period from R+P1 to R+P2.',
'203':'Climatological Standard Deviation of N analyses from the mean of the same N analyses, for analyses one year apart. The first analyses is valid for period R+P1 to R+P2.',
'204':'Average of forecast accumulations. P1 = start of accumulation period. P2 = end of accumulation period. Reference time is the start time of the first forecast, other forecasts at 6-hour intervals. Number in Ave = number of forecast used',
'205':'Average of forecast averages. P1 = start of averaging period. P2 = end of averaging period. Reference time is the start time of the first forecast, other forecasts at 6-hour intervals. Number in Ave = number of forecast used',
'206':'Average of forecast accumulations. P1 = start of accumulation period. P2 = end of accumulation period. Reference time is the start time of the first forecast, other forecasts at 12-hour intervals. Number in Ave = number of forecast used',
'207':'Average of forecast averages. P1 = start of averaging period. P2 = end of averaging period. Reference time is the start time of the first forecast, other forecasts at 12-hour intervals. Number in Ave = number of forecast used',
'255':'Missing',
}

table_4_11 = {
'0':'Reserved',
'1':'Successive times processed have same forecast time, start time of forecast is incremented.',
'2':'Successive times processed have same start time of forecast, forecast time is incremented.',
'3':'Successive times processed have start time of forecast incremented and forecast time decremented so that valid time remains constant.',
'4':'Successive times processed have start time of forecast decremented and forecast time incremented so that valid time remains constant.',
'5':'Floating subinterval of time between forecast time and end of overall time interval.(see Note 1)',
'6-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_12 = {
'0':'Mainteunknownce Mode',
'1':'Clear Air',
'2':'Precipitation',
'3-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_13 = {
'0':'No Quality Control Applied',
'1':'Quality Control Applied',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_14 = {
'0':'No Clutter Filter Used',
'1':'Clutter Filter Used',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_15 = {
'0':'Data is calculated directly from the source grid with no interpolation',
'1':'Bilinear interpolation using the 4 source grid grid-point values surrounding the nominal grid-point',
'2':'Bicubic interpolation using the 4 source grid grid-point values surrounding the nominal grid-point',
'3':'Using the value from the source grid grid-point which is nearest to the nominal grid-point',
'4':'Budget interpolation using the 4 source grid grid-point values surrounding the nominal grid-point',
'5':'Spectral interpolation using the 4 source grid grid-point values surrounding the nominal grid-point',
'6':'Neighbor-budget interpolation using the 4 source grid grid-point values surrounding the nominal grid-point',
'7-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_91 = {
'0':'Smaller than first limit',
'1':'Greater than second limit',
'2':'Between first and second limit. The range includes the first limit but not the second limit.',
'3':'Greater than first limit',
'4':'Smaller than second limit',
'5':'Smaller or equal first limit',
'6':'Greater or equal second limit',
'7':'Between first and second limit. The range includes the first limit and the second limit.',
'8':'Greater or equal first limit',
'9':'Smaller or equal second limit',
'10':'Between first and second limit. The range includes the second limit but not the first limit.',
'11':'Equal to first limit',
'12-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_201 = {
'0':'Reserved',
'1':'Rain',
'2':'Thunderstorm',
'3':'Freezing Rain',
'4':'Mixed/Ice',
'5':'Snow',
'6':'Wet Snow',
'7':'Mixture of Rain and Snow',
'8':'Ice Pellets',
'9':'Graupel',
'10':'Hail',
'11':'Drizzle',
'12':'Freezing Drizzle',
'13-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_202 = {
'0-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_203 = {
'0':'Clear',
'1':'Cumulonimbus',
'2':'Stratus',
'3':'Stratocumulus',
'4':'Cumulus',
'5':'Altostratus',
'6':'Nimbostratus',
'7':'Altocumulus',
'8':'Cirrostratus',
'9':'Cirrorcumulus',
'10':'Cirrus',
'11':'Cumulonimbus - ground-based fog beneath the lowest layer',
'12':'Stratus - ground-based fog beneath the lowest layer',
'13':'Stratocumulus - ground-based fog beneath the lowest layer',
'14':'Cumulus - ground-based fog beneath the lowest layer',
'15':'Altostratus - ground-based fog beneath the lowest layer',
'16':'Nimbostratus - ground-based fog beneath the lowest layer',
'17':'Altocumulus - ground-based fog beneath the lowest layer',
'18':'Cirrostratus - ground-based fog beneath the lowest layer',
'19':'Cirrorcumulus - ground-based fog beneath the lowest layer',
'20':'Cirrus - ground-based fog beneath the lowest layer',
'21-190':'Reserved',
'191':'Unknown',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_204 = {
'1':'Isolated (1-2%)',
'2':'Few (3-5%)',
'3':'Scattered (16-45%)',
'4':'Numerous (>45%)',
'5-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_205 = {
'0':'Aerosol not present',
'1':'Aerosol present',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_206 = {
'0':'Not Present',
'1':'Present',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_207 = {
'1':'Light',
'2':'Moderate',
'3':'Severe',
'4':'Trace',
'5':'Heavy',
'6-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_208 = {
'1':'Light',
'2':'Moderate',
'3':'Severe',
'4':'Extreme',
'5-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_209 = {
'0':'Reserved',
'1':'Stable',
'2':'Mechanically-Driven Turbulence',
'3':'Force Convection',
'4':'Free Convection',
'5-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_210 = {
'0':'Contrail Not Present',
'1':'Contrail Present',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_211 = {
'0':'Low Bypass',
'1':'High Bypass',
'2':'Non-Bypass',
'3-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_212 = {
'0':'Reserved',
'1':'Urban Land',
'2':'Agricultural',
'3':'Range Land',
'4':'Deciduous Forest',
'5':'Coniferous Forest',
'6':'Forest/Wetland',
'7':'Water',
'8':'Wetlands',
'9':'Desert',
'10':'Tundra',
'11':'Ice',
'12':'Tropical Forest',
'13':'Savannah',
'14-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_213 = {
'0':'Reserved',
'1':'Sand',
'2':'Loamy Sand',
'3':'Sandy Loam',
'4':'Silt Loam',
'5':'Organic',
'6':'Sandy Clay Loam',
'7':'Silt Clay Loam',
'8':'Clay Loam',
'9':'Sandy Clay',
'10':'Silty Clay',
'11':'Clay',
'12-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_215 = {
'0-49':'Reserved',
'50':'No-Snow/No-Cloud',
'51-99':'Reserved',
'100':'Clouds',
'101-249':'Reserved',
'250':'Snow',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_216 = {
'0-90':'Elevation in increments of 100 m',
'91-253':'Reserved',
'254':'Clouds',
'255':'Missing',
}

table_4_217 = {
'0':'Clear over water',
'1':'Clear over land',
'2':'Cloud',
'3':'No data',
'4-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_218 = {
'0':'No Scene Identified',
'1':'Green Needle-Leafed Forest',
'2':'Green Broad-Leafed Forest',
'3':'Deciduous Needle-Leafed Forest',
'4':'Deciduous Broad-Leafed Forest',
'5':'Deciduous Mixed Forest',
'6':'Closed Shrub-Land',
'7':'Open Shrub-Land',
'8':'Woody Savannah',
'9':'Savannah',
'10':'Grassland',
'11':'Permanent Wetland',
'12':'Cropland',
'13':'Urban',
'14':'Vegetation / Crops',
'15':'Permanent Snow / Ice',
'16':'Barren Desert',
'17':'Water Bodies',
'18':'Tundra',
'19':'Warm Liquid Water Cloud',
'20':'Supercooled Liquid Water Cloud',
'21':'Mixed Phase Cloud',
'22':'Optically Thin Ice Cloud',
'23':'Optically Thick Ice Cloud',
'24':'Multi-Layeblack Cloud',
'25-96':'Reserved',
'97':'Snow / Ice on Land',
'98':'Snow / Ice on Water',
'99':'Sun-Glint',
'100':'General Cloud',
'101':'Low Cloud / Fog / Stratus',
'102':'Low Cloud / Stratocumulus',
'103':'Low Cloud / Unknown Type',
'104':'Medium Cloud / Nimbostratus',
'105':'Medium Cloud / Altostratus',
'106':'Medium Cloud / Unknown Type',
'107':'High Cloud / Cumulus',
'108':'High Cloud / Cirrus',
'109':'High Cloud / Unknown Type',
'110':'Unknown Cloud Type',
'111':'Single layer water cloud',
'112':'Single layer ice cloud',
'113-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_222 = {
'0':'No',
'1':'Yes',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_223 = {
'0':'No Fire Detected',
'1':'Possible Fire Detected',
'2':'Probable Fire Detected',
'3':'Missing',
'4-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_224 = {
'0':'No Risk Area',
'1':'Reserved',
'2':'General Thunderstorm Risk Area',
'3':'Reserved',
'4':'Slight Risk Area',
'5':'Reserved',
'6':'Moderate Risk Area',
'7':'Reserved',
'8':'High Risk Area',
'9-10':'Reserved',
'11':'Dry Thunderstorm (Dry Lightning) Risk Area',
'12-13':'Reserved',
'14':'Critical Risk Area',
'15-17':'Reserved',
'18':'Extreamly Critical Risk Area',
'19-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_227 = {
'1':'General',
'2':'Convective',
'3':'Stratiform',
'4':'Freezing',
'5-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_228 = {
'1':'Trace',
'2':'Light',
'3':'Moderate',
'4':'Severe',
'6-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_233 = {
'0':['Ozone','O3'],
'1':['Water Vapour','H2O'],
'2':['Methane','CH4'],
'3':['Carbon Dioxide','CO2'],
'4':['Carbon Monoxide','CO'],
'5':['Nitrogen Dioxide','NO2'],
'6':['Nitrous Oxide','N2O'],
'7':['Formaldehyde','HCHO'],
'8':['Sulphur Dioxide','SO2'],
'9':['Ammonia','NH3'],
'10':['Ammonium','NH4+'],
'11':['Nitrogen Monoxide','NO'],
'12':['Atomic Oxygen','O'],
'13':['Nitrate Radical','NO3'],
'14':['Hydroperoxyl Radical','HO2'],
'15':['Dinitrogen Pentoxide','H2O5'],
'16':['Nitrous Acid','HONO'],
'17':['Nitric Acid','HNO3'],
'18':['Peroxynitric Acid','HO2NO2'],
'19':['Hydrogen Peroxide','H2O2'],
'20':['Molecular Hydrogen','H'],
'21':['Atomic Nitrogen','N'],
'22':['Sulphate','SO42-'],
'23':['Radon','Rn'],
'24':['Elemental Mercury','Hg(O)'],
'25':['Divalent Mercury','Hg2+'],
'26':['Atomic Chlorine','Cl'],
'27':['Chlorine Monoxide','ClO'],
'28':['Dichlorine Peroxide','Cl2O2'],
'29':['Hypochlorous Acid','HClO'],
'30':['Chlorine Nitrate','ClONO2'],
'31':['Chlorine Dioxide','ClO2'],
'32':['Atomic Bromide','Br'],
'33':['Bromine Monoxide','BrO'],
'34':['Bromine Chloride','BrCl'],
'35':['Hydrogen Bromide','HBr'],
'36':['Hypobromous Acid','HBrO'],
'37':['Bromine Nitrate','BrONO2'],
'38':['Oxygen','O2'],
'39-9999':['Reserved','unknown'],
'10000':['Hydroxyl Radical','OH'],
'10001':['Methyl Peroxy Radical','CH3O2'],
'10002':['Methyl Hydroperoxide','CH3O2H'],
'10003':['Reserved','unknown'],
'10004':['Methanol','CH3OH'],
'10005':['Formic Acid','CH3OOH'],
'10006':['Hydrogen Cyanide','HCN'],
'10007':['Aceto Nitrile','CH3CN'],
'10008':['Ethane','C2H6'],
'10009':['Ethene (= Ethylene)','C2H4'],
'10010':['Ethyne (= Acetylene)','C2H2'],
'10011':['Ethanol','C2H5OH'],
'10012':['Acetic Acid','C2H5OOH'],
'10013':['Peroxyacetyl Nitrate','CH3C(O)OONO2'],
'10014':['Propane','C3H8'],
'10015':['Propene','C3H6'],
'10016':['Butanes','C4H10'],
'10017':['Isoprene','C5H10'],
'10018':['Alpha Pinene','C10H16'],
'10019':['Beta Pinene','C10H16'],
'10020':['Limonene','C10H16'],
'10021':['Benzene','C6H6'],
'10022':['Toluene','C7H8'],
'10023':['Xylene','C8H10'],
'10024-10499':['Reserved','unknown'],
'10500':['Dimethyl Sulphide','CH3SCH3'],
'10501-20000':['Reserved','unknown'],
'20001':['Hydrogen Chloride','HCL'],
'20002':['CFC-11','unknown'],
'20003':['CFC-12','unknown'],
'20004':['CFC-113','unknown'],
'20005':['CFC-113a','unknown'],
'20006':['CFC-114','unknown'],
'20007':['CFC-115','unknown'],
'20008':['HCFC-22','unknown'],
'20009':['HCFC-141b','unknown'],
'20010':['HCFC-142b','unknown'],
'20011':['Halon-1202','unknown'],
'20012':['Halon-1211','unknown'],
'20013':['Halon-1301','unknown'],
'20014':['Halon-2402','unknown'],
'20015':['Methyl Chloride (HCC-40)','unknown'],
'20016':['Carbon Tetrachloride (HCC-10)','unknown'],
'20017':['HCC-140a','CH3CCl3'],
'20018':['Methyl Bromide (HBC-40B1)','unknown'],
'20019':['Hexachlorocyclohexane (HCH)','unknown'],
'20020':['Alpha Hexachlorocyclohexane','unknown'],
'20021':['Hexachlorobiphenyl (PCB-153)','unknown'],
'20022-29999':['Reserved','unknown'],
'30000':['Radioactive Pollutant (Tracer, defined by originating centre)','unknown'],
'30001-50000':['Reserved','unknown'],
'60000':['HOx Radical (OH+HO2)','unknown'],
'60001':['Total Inorganic and Organic Peroxy Radicals (HO2+RO2)','RO2'],
'60002':['Passive Ozone','unknown'],
'60003':['NOx Expressed As Nitrogen','NOx'],
'60004':['All Nitrogen Oxides (NOy) Expressed As Nitrogen','NOy'],
'60005':['Total Inorganic Chlorine','Clx'],
'60006':['Total Inorganic Bromine','Brx'],
'60007':['Total Inorganic Chlorine Except HCl, ClONO2: ClOx','unknown'],
'60008':['Total Inorganic Bromine Except Hbr, BrONO2:BrOx','unknown'],
'60009':['Lumped Alkanes','unknown'],
'60010':['Lumped Alkenes','unknown'],
'60011':['Lumped Aromatic Coumpounds','unknown'],
'60012':['Lumped Terpenes','unknown'],
'60013':['Non-Methane Volatile Organic Compounds Expressed as Carbon','NMVOC'],
'60014':['Anthropogenic Non-Methane Volatile Organic Compounds Expressed as Carbon','aNMVOC'],
'60015':['Biogenic Non-Methane Volatile Organic Compounds Expressed as Carbon','bNMVOC'],
'60016':['Lumped Oxygenated Hydrocarbons','OVOC'],
'60017-61999':['Reserved','unknown'],
'62000':['Total Aerosol','unknown'],
'62001':['Dust Dry','unknown'],
'62002':['water In Ambient','unknown'],
'62003':['Ammonium Dry','unknown'],
'62004':['Nitrate Dry','unknown'],
'62005':['Nitric Acid Trihydrate','unknown'],
'62006':['Sulphate Dry','unknown'],
'62007':['Mercury Dry','unknown'],
'62008':['Sea Salt Dry','unknown'],
'62009':['Black Carbon Dry','unknown'],
'62010':['Particulate Organic Matter Dry','unknown'],
'62011':['Primary Particulate Organic Matter Dry','unknown'],
'62012':['Secondary Particulate Organic Matter Dry','unknown'],
'62013':['Black carbon hydrophilic dry','unknown'],
'62014':['Black carbon hydrophobic dry','unknown'],
'62015':['Particulate organic matter hydrophilic dry','unknown'],
'62016':['Particulate organic matter hydrophobic dry','unknown'],
'62017':['Nitrate hydrophilic dry','unknown'],
'62018':['Nitrate hydrophobic dry','unknown'],
'62019':['Reserved','unknown'],
'62020':['Smoke - high absorption','unknown'],
'62021':['Smoke - low absorption','unknown'],
'62022':['Aerosol - high absorption','unknown'],
'62023':['Aerosol - low absorption','unknown'],
'62024':['Reserved','unknown'],
'62025':['Volcanic ash','unknown'],
'62036':['Brown Carbon Dry','unknown'],
'62037-65534':['Reserved','unknown'],
'65535':['Missing','unknown'],
}

table_4_234 = {
'1':'Crops, mixed farming',
'2':'Short grass',
'3':'Evergreen needleleaf trees',
'4':'Deciduous needleleaf trees',
'5':'Deciduous broadleaf trees',
'6':'Evergreen broadleaf trees',
'7':'Tall grass',
'8':'Desert',
'9':'Tundra',
'10':'Irrigated corps',
'11':'Semidesert',
'12':'Ice caps and glaciers',
'13':'Bogs and marshes',
'14':'Inland water',
'15':'Ocean',
'16':'Evergreen shrubs',
'17':'Deciduous shrubs',
'18':'Mixed forest',
'19':'Interrupted forest',
'20':'Water and land mixtures',
'21-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_235 = {
'0':'Total Wave Spectrum (combined wind waves and swell)',
'1':'Generalized Partition',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_236 = {
'1':'Coarse',
'2':'Medium',
'3':'Medium-fine',
'4':'Fine',
'5':'Very-fine',
'6':'Organic',
'7':'Tropical-organic',
'8-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_238 = {
'0':'Reserved',
'1':'Aviation',
'2':'Lightning',
'3':'Biogenic Sources',
'4':'Anthropogenic sources',
'5':'Wild fires',
'6':'Natural sources',
'7':'Bio-fuel',
'8':'Volcanoes',
'9':'Fossil-fuel',
'10':'Wetlands',
'11':'Oceans',
'12':'Elevated anthropogenic sources',
'13':'Surface anthropogenic sources',
'14':'Agriculture livestock',
'15':'Agriculture soils',
'16':'Agriculture waste burning',
'17':'Agriculture (all)',
'18':'Residential, commercial and other combustion',
'19':'Power generation',
'20':'Super power stations',
'21':'Fugitives',
'22':'Industrial process',
'23':'Solvents',
'24':'Ships',
'25':'Wastes',
'26':'Road transportation',
'27':'Off-road transportation',
'28-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_239 = {
'0':'Reserved',
'1':'Bog',
'2':'Drained',
'3':'Fen',
'4':'Floodplain',
'5':'Mangrove',
'6':'Marsh',
'7':'Rice',
'8':'Riverine',
'9':'Salt Marsh',
'10':'Swamp',
'11':'Upland',
'12':'Wet tundra',
'13-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_243 = {
'0':'Reserved',
'1':'Evergreen broadleaved forest',
'2':'Deciduous broadleaved closed forest',
'3':'Deciduous broadleaved open forest',
'4':'Evergreen needle-leaf forest',
'5':'Deciduous needle-leaf forest',
'6':'Mixed leaf trees',
'7':'Fresh water flooded trees',
'8':'Saline water flooded trees',
'9':'Mosaic tree/natural vegetation',
'10':'Burnt tree cover',
'11':'Evergreen shurbs closed-open',
'12':'Deciduous shurbs closed-open',
'13':'Herbaceous vegetation closed-open',
'14':'Sparse herbaceous or grass',
'15':'Flooded shurbs or herbaceous',
'16':'Cultivated and managed areas',
'17':'Mosaic crop/tree/natural vegetation',
'18':'Mosaic crop/shrub/grass',
'19':'Bare areas',
'20':'Water',
'21':'Snow and ice',
'22':'Artificial surface',
'23':'Ocean',
'24':'Irrigated croplands',
'25':'Rain fed croplands',
'26':'Mosaic cropland (50-70%)-vegetation (20-50%)',
'27':'Mosaic vegetation (50-70%)-cropland (20-50%)',
'28':'Closed broadleaved evergreen forest',
'29':'Closed needle-leaved evergreen forest',
'30':'Open needle-leaved deciduous forest',
'31':'Mixed broadleaved and needle-leave forest',
'32':'Mosaic shrubland (50-70%)-grassland (20-50%)',
'33':'Mosaic grassland (50-70%)-shrubland (20-50%)',
'34':'Closed to open shrubland',
'35':'Sparse vegetation',
'36':'Closed to open forest regularly flooded',
'37':'Closed forest or shrubland permanently flooded',
'38':'Closed to open grassland regularly flooded',
'39':'Undefined',
'40-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_244 = {
'0':'No Quality Information Available',
'1':'Failed',
'2':'Passed',
'3-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_246 = {
'0':'No thunderstorm occurrence',
'1':'Weak thunderstorm',
'2':'Moderate thunderstorm',
'3':'Severe thunderstorm',
'4-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_247 = {
'0':'No precipitation occurrence',
'1':'Light precipitation',
'2':'Moderate precipitation',
'3':'Heavy precipitation',
'4-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_248 = {
'0':'Nearest forecast or analysis time to specified local time',
'1':'Interpolated to be valid at the specified local time',
'2-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_249 = {
'1':'Showers',
'2':'Intermittent',
'3':'Continuous',
'4-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_250 = {
'0':'Reserved',
'1':'South-West',
'2':'South',
'3':'South-East',
'4':'West',
'5':'No direction',
'6':'East',
'7':'North-West',
'8':'North',
'9':'North-East',
'10-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_4_251 = {
'0':'Undefined Sequence',
'1':'Geometric sequence,(see Note 1)',
'2':'Arithmetic sequence,(see Note 2)',
'3-191':'Reserved',
'192-254':'Reserved for Local Use',
'255':'Missing',
}

table_scale_time_hours = {
'0': 60.,
'1': 1.,
'2': float(1.0/24.0),
'3': float(1.0/720.0),
'4': float(1.0/(365.0*24.0)),
'5': float(1.0/(10.0*365.0*24.0)),
'6': float(1.0/(30.0*365.0*24.0)),
'7': float(1.0/(100.0*365.0*24.0)),
'8': 1.,
'9': 1.,
'10': 3.,
'11': 6.,
'12': 12.,
'13': 3600.,
'14-255': 1.}

# ----------------------------------------------------------------------------------------
# Source: https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/blob/develop/wgrib2/Level.c
#
# The dictionary key is the Section 4.5 coded value.  The value is a list where the
# index 0 is the string to use for level and index 1 is the string for a layer.
# ----------------------------------------------------------------------------------------
table_wgrib2_level_string = {
'0': ["reserved","reserved"],
'1': ["surface","reserved"],
'2': ["cloud base","reserved"],
'3': ["cloud top","reserved"],
'4': ["0C isotherm","reserved"],
'5': ["level of adiabatic condensation from sfc","reserved"],
'6': ["max wind","reserved"],
'7': ["tropopause","reserved"],
'8': ["top of atmosphere","reserved"],
'9': ["sea bottom","reserved"],
'10': ["entire atmosphere","reserved"],
'11': ["cumulonimbus base","reserved"],
'12': ["cumulonimbus top","reserved"],
'13': ["lowest level %g%% integrated cloud cover","reserved"],
'14': ["level of free convection","reserved"],
'15': ["convection condensation level","reserved"],
'16': ["level of neutral buoyancy","reserved"],
'17': ["reserved","reserved"],
'18': ["reserved","reserved"],
'19': ["reserved","reserved"],
'20': ["%g K level","reserved"],
'21': ["lowest level > %g kg/m^3","reserved"],
'22': ["highest level > %g kg/m^3","reserved"],
'23': ["lowest level > %g Bq/m^3","reserved"],
'24': ["highest level > %g Bg/m^3","reserved"],
'25': ["reserved","reserved"],
'26': ["reserved","reserved"],
'27': ["reserved","reserved"],
'28': ["reserved","reserved"],
'29': ["reserved","reserved"],
'30': ["reserved","reserved"],
'31': ["reserved","reserved"],
'32': ["reserved","reserved"],
'33': ["reserved","reserved"],
'34': ["reserved","reserved"],
'35': ["reserved","reserved"],
'36': ["reserved","reserved"],
'37': ["reserved","reserved"],
'38': ["reserved","reserved"],
'39': ["reserved","reserved"],
'40': ["reserved","reserved"],
'41': ["reserved","reserved"],
'42': ["reserved","reserved"],
'43': ["reserved","reserved"],
'44': ["reserved","reserved"],
'45': ["reserved","reserved"],
'46': ["reserved","reserved"],
'47': ["reserved","reserved"],
'48': ["reserved","reserved"],
'49': ["reserved","reserved"],
'50': ["reserved","reserved"],
'51': ["reserved","reserved"],
'52': ["reserved","reserved"],
'53': ["reserved","reserved"],
'54': ["reserved","reserved"],
'55': ["reserved","reserved"],
'56': ["reserved","reserved"],
'57': ["reserved","reserved"],
'58': ["reserved","reserved"],
'59': ["reserved","reserved"],
'60': ["reserved","reserved"],
'61': ["reserved","reserved"],
'62': ["reserved","reserved"],
'63': ["reserved","reserved"],
'64': ["reserved","reserved"],
'65': ["reserved","reserved"],
'66': ["reserved","reserved"],
'67': ["reserved","reserved"],
'68': ["reserved","reserved"],
'69': ["reserved","reserved"],
'70': ["reserved","reserved"],
'71': ["reserved","reserved"],
'72': ["reserved","reserved"],
'73': ["reserved","reserved"],
'74': ["reserved","reserved"],
'75': ["reserved","reserved"],
'76': ["reserved","reserved"],
'77': ["reserved","reserved"],
'78': ["reserved","reserved"],
'79': ["reserved","reserved"],
'80': ["reserved","reserved"],
'81': ["reserved","reserved"],
'82': ["reserved","reserved"],
'83': ["reserved","reserved"],
'84': ["reserved","reserved"],
'85': ["reserved","reserved"],
'86': ["reserved","reserved"],
'87': ["reserved","reserved"],
'88': ["reserved","reserved"],
'89': ["reserved","reserved"],
'90': ["reserved","reserved"],
'91': ["reserved","reserved"],
'92': ["reserved","reserved"],
'93': ["reserved","reserved"],
'94': ["reserved","reserved"],
'95': ["reserved","reserved"],
'96': ["reserved","reserved"],
'97': ["reserved","reserved"],
'98': ["reserved","reserved"],
'99': ["reserved","reserved"],
'100': ["%g mb","%g-%g mb"],
'101': ["mean sea level","reserved"],
'102': ["%g m above mean sea level","%g-%g m above mean sea level"],
'103': ["%g m above ground","%g-%g m above ground"],
'104': ["%g sigma level","%g-%g sigma layer"],
'105': ["%g hybrid level","%g-%g hybrid layer"],
'106': ["%g m underground","%g-%g m underground"],
'107': ["%g K isentropic level","%g-%g K isentropic layer"],
'108': ["%g mb above ground","%g-%g mb above ground"],
'109': ["PV=%g (Km^2/kg/s) surface","reserved"],
'110': ["reserved","reserved"],
'111': ["%g Eta level","%g-%g Eta layer"],
'112': ["reserved","reserved"],
'113': ["%g logarithmic hybrid level","reserved"],
'114': ["snow level","reserved"],
'115': ["%g sigma height level","%g-%g sigma heigh layer"],
'116': ["reserved","reserved"],
'117': ["mixed layer depth","reserved"],
'118': ["%g hybrid height level","%g-%g hybrid height layer"],
'119': ["%g hybrid pressure level","%g-%g hybrid pressure layer"],
'120': ["reserved","reserved"],
'121': ["reserved","reserved"],
'122': ["reserved","reserved"],
'123': ["reserved","reserved"],
'124': ["reserved","reserved"],
'125': ["reserved","reserved"],
'126': ["reserved","reserved"],
'127': ["reserved","reserved"],
'128': ["reserved","reserved"],
'129': ["reserved","reserved"],
'130': ["reserved","reserved"],
'131': ["reserved","reserved"],
'132': ["reserved","reserved"],
'133': ["reserved","reserved"],
'134': ["reserved","reserved"],
'135': ["reserved","reserved"],
'136': ["reserved","reserved"],
'137': ["reserved","reserved"],
'138': ["reserved","reserved"],
'139': ["reserved","reserved"],
'140': ["reserved","reserved"],
'141': ["reserved","reserved"],
'142': ["reserved","reserved"],
'143': ["reserved","reserved"],
'144': ["reserved","reserved"],
'145': ["reserved","reserved"],
'146': ["reserved","reserved"],
'147': ["reserved","reserved"],
'148': ["reserved","reserved"],
'149': ["reserved","reserved"],
'150': ["%g generalized vertical height coordinate","reserved"],
'151': ["soil level %g","reserved"],
'152': ["reserved","reserved"],
'153': ["reserved","reserved"],
'154': ["reserved","reserved"],
'155': ["reserved","reserved"],
'156': ["reserved","reserved"],
'157': ["reserved","reserved"],
'158': ["reserved","reserved"],
'159': ["reserved","reserved"],
'160': ["%g m below sea level","%g-%g m below sea level"],
'161': ["%g m below water surface","%g-%g m ocean layer"],
'162': ["lake or river bottom","reserved"],
'163': ["bottom of sediment layer","reserved"],
'164': ["bottom of thermally active sediment layer","reserved"],
'165': ["bottom of sediment layer penetrated by thermal wave","reserved"],
'166': ["maxing layer","reserved"],
'167': ["bottom of root zone","reserved"],
'168': ["reserved","reserved"],
'169': ["reserved","reserved"],
'170': ["reserved","reserved"],
'171': ["reserved","reserved"],
'172': ["reserved","reserved"],
'173': ["reserved","reserved"],
'174': ["top surface of ice on sea, lake or river","reserved"],
'175': ["top surface of ice, und snow on sea, lake or river","reserved"],
'176': ["bottom surface ice on sea, lake or river","reserved"],
'177': ["deep soil","reserved"],
'178': ["reserved","reserved"],
'179': ["top surface of glacier ice and inland ice","reserved"],
'180': ["deep inland or glacier ice","reserved"],
'181': ["grid tile land fraction as a model surface","reserved"],
'182': ["grid tile water fraction as a model surface","reserved"],
'183': ["grid tile ice fraction on sea, lake or river as a model surface","reserved"],
'184': ["grid tile glacier ice and inland ice fraction as a model surface","reserved"],
'185': ["reserved","reserved"],
'186': ["reserved","reserved"],
'187': ["reserved","reserved"],
'188': ["reserved","reserved"],
'189': ["reserved","reserved"],
'190': ["reserved","reserved"],
'191': ["reserved","reserved"],
'192': ["reserved","reserved"],
'193': ["reserved","reserved"],
'194': ["reserved","reserved"],
'195': ["reserved","reserved"],
'196': ["reserved","reserved"],
'197': ["reserved","reserved"],
'198': ["reserved","reserved"],
'199': ["reserved","reserved"],
'200': ["entire atmosphere (considered as a single layer)","reserved"],
'201': ["entire ocean (considered as a single layer)","reserved"],
'202': ["reserved","reserved"],
'203': ["reserved","reserved"],
'204': ["highest tropospheric freezing level","reserved"],
'205': ["reserved","reserved"],
'206': ["grid scale cloud bottom level","reserved"],
'207': ["grid scale cloud top level","reserved"],
'208': ["reserved","reserved"],
'209': ["boundary layer cloud bottom level","reserved"],
'210': ["boundary layer cloud top level","reserved"],
'211': ["boundary layer cloud layer","reserved"],
'212': ["low cloud bottom level","reserved"],
'213': ["low cloud top level","reserved"],
'214': ["low cloud layer","reserved"],
'215': ["cloud ceiling","reserved"],
'216': ["reserved","reserved"],
'217': ["reserved","reserved"],
'218': ["reserved","reserved"],
'219': ["reserved","reserved"],
'220': ["planetary boundary layer","reserved"],
'221': ["layer between two hybrid levels","reserved"],
'222': ["middle cloud bottom level","reserved"],
'223': ["middle cloud top level","reserved"],
'224': ["middle cloud layer","reserved"],
'225': ["reserved","reserved"],
'226': ["reserved","reserved"],
'227': ["reserved","reserved"],
'228': ["reserved","reserved"],
'229': ["reserved","reserved"],
'230': ["reserved","reserved"],
'231': ["reserved","reserved"],
'232': ["high cloud bottom level","reserved"],
'233': ["high cloud top level","reserved"],
'234': ["high cloud layer","reserved"],
'235': ["%gC ocean isotherm","%g-%gC ocean isotherm layer"],
'236': ["layer between two depths below ocean surface","%g-%g m ocean layer"],
'237': ["bottom of ocean mixed layer","reserved"],
'238': ["bottom of ocean isothermal layer","reserved"],
'239': ["layer ocean surface and 26C ocean isothermal level","reserved"],
'240': ["ocean mixed layer","reserved"],
'241': ["%g in sequence","reserved"],
'242': ["convective cloud bottom level","reserved"],
'243': ["convective cloud top level","reserved"],
'244': ["convective cloud layer","reserved"],
'245': ["lowest level of the wet bulb zero","reserved"],
'246': ["maximum equivalent potential temperature level","reserved"],
'247': ["equilibrium level","reserved"],
'248': ["shallow convective cloud bottom level","reserved"],
'249': ["shallow convective cloud top level","reserved"],
'250': ["reserved","reserved"],
'251': ["deep convective cloud bottom level","reserved"],
'252': ["deep convective cloud top level","reserved"],
'253': ["lowest bottom level of supercooled liquid water layer","reserved"],
'254': ["highest top level of supercooled liquid water layer","reserved"],
'255': ["missing","reserved"],
}

