name: Build and Test on macOS

on: [push, pull_request]

jobs:
  build-macos:
    
    name: Python (${{ matrix.python-version }})
    runs-on: macos-latest
    env:
      CC: gcc-12
    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]
   
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install macOS Dependencies
      run: |
        brew install jasper libpng
        brew tap eengl/nceplibs
        brew install nceplibs-g2c

    - name: Install python dependencies via pip
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade setuptools
        python3 -m pip install --upgrade wheel
        python3 -m pip install -r requirements.txt

    - name: Install grib2io and test
      run: |
        python --version
        pip install .
        cd /tmp # Get out of source package
        python -c "import grib2io; print(grib2io)"
        python -c "import xarray; print(xarray.backends.list_engines().keys())"
