name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff Check
        run: ruff check .
      - name: Run Ruff Format
        run: ruff format --diff --check .
